ALTER SESSION SET NLS_DATE_FORMAT = 'dd-mm-yyyy hh24:mi:ss';
GRANT CREATE TABLESPACE, DROP TABLESPACE, ALTER TABLESPACE  TO RMV;
ALTER USER RMV QUOTA UNLIMITED ON T1;
ALTER USER RMV QUOTA UNLIMITED ON T2;
ALTER USER RMV QUOTA UNLIMITED ON T3;
ALTER USER RMV QUOTA UNLIMITED ON T4;

-- DROP TABLESPACE t1 INCLUDING CONTENTS AND DATAFILES;
-- DROP TABLESPACE t2 INCLUDING CONTENTS AND DATAFILES;
-- DROP TABLESPACE t3 INCLUDING CONTENTS AND DATAFILES;
-- DROP TABLESPACE t4 INCLUDING CONTENTS AND DATAFILES;

CREATE TABLESPACE t1
    DATAFILE 't1_rmv.dbf'
    SIZE 7 M
    AUTOEXTEND ON
    MAXSIZE UNLIMITED
    EXTENT MANAGEMENT LOCAL;

CREATE TABLESPACE t2
    DATAFILE 't2_rmv.dbf'
    SIZE 7 M
    AUTOEXTEND ON
    MAXSIZE UNLIMITED
    EXTENT MANAGEMENT LOCAL;

CREATE TABLESPACE t3
    DATAFILE 't3_rmv.dbf'
    SIZE 7 M
    AUTOEXTEND ON
    MAXSIZE UNLIMITED
    EXTENT MANAGEMENT LOCAL;

CREATE TABLESPACE t4
    DATAFILE 't4_rmv.dbf'
    SIZE 7 M
    AUTOEXTEND ON
    MAXSIZE UNLIMITED
    EXTENT MANAGEMENT LOCAL;

-- Задание 1, 5
-- DROP TABLE T_RANGE;

CREATE TABLE T_RANGE
(
    id      NUMBER,
    TIME_ID DATE
)
PARTITION BY RANGE (id)
(
    PARTITION p0 VALUES LESS THAN (100) TABLESPACE t1,
    PARTITION p1 VALUES LESS THAN (200) TABLESPACE t2,
    PARTITION p2 VALUES LESS THAN (300) TABLESPACE t3,
    PARTITION PMAX VALUES LESS THAN (MAXVALUE) TABLESPACE t4
);

BEGIN
    FOR i IN 1..400
    LOOP
        INSERT INTO T_RANGE(id, time_id) VALUES (i, SYSDATE);
    END LOOP;
    COMMIT;
END;
/

SELECT * FROM T_RANGE PARTITION(p0);
SELECT * FROM T_RANGE PARTITION(p1);
SELECT * FROM T_RANGE PARTITION(p2);
SELECT * FROM T_RANGE PARTITION(pmax);

SELECT TABLE_NAME, PARTITION_NAME, HIGH_VALUE, TABLESPACE_NAME
FROM USER_TAB_PARTITIONS
WHERE TABLE_NAME = 'T_RANGE';

-- Задание 2, 5
-- DROP TABLE T_INTERVAL;

CREATE TABLE T_INTERVAL
(
    id      NUMBER,
    time_id DATE
)
PARTITION BY RANGE (time_id)
INTERVAL (NUMTOYMINTERVAL(1, 'MONTH'))
(
    PARTITION p0 VALUES LESS THAN (TO_DATE('1-12-2010', 'dd-mm-yyyy')) TABLESPACE t1,
    PARTITION p1 VALUES LESS THAN (TO_DATE('1-12-2015', 'dd-mm-yyyy')) TABLESPACE t2,
    PARTITION p2 VALUES LESS THAN (TO_DATE('1-12-2020', 'dd-mm-yyyy')) TABLESPACE t3
);

INSERT INTO T_INTERVAL(id, time_id) VALUES (50, '01-02-2008');
INSERT INTO T_INTERVAL(id, time_id) VALUES (105, '01-01-2009');
INSERT INTO T_INTERVAL(id, time_id) VALUES (105, '01-01-2007');
INSERT INTO T_INTERVAL(id, time_id) VALUES (205, '01-01-2019');
INSERT INTO T_INTERVAL(id, time_id) VALUES (305, '01-01-2013');
INSERT INTO T_INTERVAL(id, time_id) VALUES (405, '01-01-2017');
INSERT INTO T_INTERVAL(id, time_id) VALUES (505, '01-01-2022');
COMMIT;


SELECT * FROM T_INTERVAL PARTITION (p0);
SELECT * FROM T_INTERVAL PARTITION (p1);
SELECT * FROM T_INTERVAL PARTITION (p2);

SELECT TABLE_NAME, PARTITION_NAME, HIGH_VALUE, TABLESPACE_NAME
FROM USER_TAB_PARTITIONS
WHERE TABLE_NAME = 'T_INTERVAL';

-- Задание 3, 5
-- DROP TABLE T_HASH;

CREATE TABLE T_HASH
(
    str VARCHAR2(50),
    id  NUMBER
)
PARTITION BY HASH (str)
(
    PARTITION k0 TABLESPACE t1,
    PARTITION k1 TABLESPACE t2,
    PARTITION k2 TABLESPACE t3,
    PARTITION k3 TABLESPACE t4
);

INSERT INTO T_HASH (str, id) VALUES ('qwerty', 1);
INSERT INTO T_HASH (str, id) VALUES ('some string', 2);
INSERT INTO T_HASH (str, id) VALUES ('abcdefg', 3);
INSERT INTO T_HASH (str, id) VALUES ('bbbbbbbb', 4);
INSERT INTO T_HASH (str, id) VALUES ('xx', 7);
INSERT INTO T_HASH (str, id) VALUES ('uuuu', 14);
INSERT INTO T_HASH (str, id) VALUES ('qwertyqwerty', 32);
COMMIT;

SELECT * FROM T_HASH PARTITION (k0);
SELECT * FROM T_HASH PARTITION (k1);
SELECT * FROM T_HASH PARTITION (k2);
SELECT * FROM T_HASH PARTITION (k3);

-- Задание 4, 5
-- DROP TABLE T_LIST;

CREATE TABLE T_LIST
(
    obj CHAR(3)
)
PARTITION BY LIST(obj)
(
    PARTITION l0 VALUES ('a') TABLESPACE t1,
    PARTITION l1 VALUES ('b') TABLESPACE t2,
    PARTITION l2 VALUES ('c') TABLESPACE t3,
    PARTITION l3 VALUES (DEFAULT) TABLESPACE t4
);

INSERT INTO T_LIST(obj) VALUES('a');
INSERT INTO T_LIST(obj) VALUES('b');
INSERT INTO T_LIST(obj) VALUES('c');
INSERT INTO T_LIST(obj) VALUES('d');
INSERT INTO T_LIST(obj) VALUES('e');
COMMIT;

SELECT * FROM T_LIST PARTITION (l0);
SELECT * FROM T_LIST PARTITION (l1);
SELECT * FROM T_LIST PARTITION (l2);
SELECT * FROM T_LIST PARTITION (l3);

-- Задание 6
ALTER TABLE T_RANGE ENABLE ROW MOVEMENT;
SELECT * FROM T_RANGE PARTITION(PMAX) WHERE id = 300;
UPDATE T_RANGE SET id = 2 WHERE id = 300;
SELECT * FROM T_RANGE PARTITION(p0) WHERE id = 2;

ALTER TABLE T_INTERVAL ENABLE ROW MOVEMENT;
SELECT * FROM T_INTERVAL PARTITION(p0) WHERE id = 50;
UPDATE T_INTERVAL SET time_id = TO_DATE('01-02-2017', 'dd-mm-yyyy') WHERE id = 50;
SELECT * FROM T_INTERVAL PARTITION(p2) WHERE id = 50;

ALTER TABLE T_HASH ENABLE ROW MOVEMENT;
SELECT * FROM T_HASH WHERE id = 3;
UPDATE T_HASH SET str = 'zxcvbnm' WHERE id = 3;
SELECT * FROM T_HASH WHERE id = 3;

ALTER TABLE T_LIST ENABLE ROW MOVEMENT;
SELECT * FROM T_LIST PARTITION(l0) WHERE obj = 'a';
UPDATE T_LIST SET obj = 'b' WHERE obj = 'a';
SELECT * FROM T_LIST PARTITION(l1) WHERE obj = 'b';

-- Задание 7
ALTER TABLE T_RANGE MERGE PARTITIONS p1, p2 INTO PARTITION p5 TABLESPACE t4;
SELECT * FROM T_RANGE PARTITION(p5);
SELECT TABLE_NAME, PARTITION_NAME, HIGH_VALUE, TABLESPACE_NAME
FROM USER_TAB_PARTITIONS
WHERE TABLE_NAME = 'T_RANGE';

-- Задание 8
ALTER TABLE T_RANGE SPLIT PARTITION p5 AT (200)
INTO (PARTITION p1 TABLESPACE t1, PARTITION p2 TABLESPACE t2);
SELECT * FROM T_RANGE PARTITION(p1);
SELECT * FROM T_RANGE PARTITION(p2);
SELECT TABLE_NAME, PARTITION_NAME, HIGH_VALUE, TABLESPACE_NAME
FROM USER_TAB_PARTITIONS
WHERE TABLE_NAME = 'T_RANGE';

-- Задание 9
-- DROP TABLE T_RANGE1;

CREATE TABLE T_RANGE1
(
    id      NUMBER,
    TIME_ID DATE
);

ALTER TABLE T_RANGE EXCHANGE PARTITION p0 WITH TABLE T_RANGE1 WITHOUT VALIDATION;

SELECT * FROM T_RANGE PARTITION (p0);
SELECT * FROM T_RANGE1;

COMMIT;