-- 3. Вычисление итогов предоставленных услуг помесячно, за квартал, за полгода, за год
SELECT DISTINCT
    EXTRACT(YEAR FROM b.booking_date) AS "Год",
    EXTRACT(MONTH FROM b.booking_date) AS "Месяц",
    TO_CHAR(b.booking_date, 'Month', 'NLS_DATE_LANGUAGE=RUSSIAN') AS "Название месяца",
    SUM(b.total_price) OVER (PARTITION BY EXTRACT(YEAR FROM b.booking_date), EXTRACT(MONTH FROM b.booking_date)) AS "Итог за месяц",
    SUM(b.total_price) OVER (PARTITION BY EXTRACT(YEAR FROM b.booking_date), 
        CASE 
            WHEN EXTRACT(MONTH FROM b.booking_date) BETWEEN 1 AND 3 THEN 1
            WHEN EXTRACT(MONTH FROM b.booking_date) BETWEEN 4 AND 6 THEN 2
            WHEN EXTRACT(MONTH FROM b.booking_date) BETWEEN 7 AND 9 THEN 3
            ELSE 4
        END) AS "Итог за квартал",
    SUM(b.total_price) OVER (PARTITION BY EXTRACT(YEAR FROM b.booking_date),
        CASE WHEN EXTRACT(MONTH FROM b.booking_date) <= 6 THEN 1 ELSE 2 END) AS "Итог за полугодие",
    SUM(b.total_price) OVER (PARTITION BY EXTRACT(YEAR FROM b.booking_date)) AS "Итог за год",
    COUNT(b.id) OVER (PARTITION BY EXTRACT(YEAR FROM b.booking_date), EXTRACT(MONTH FROM b.booking_date)) AS "Количество бронирований"
FROM Booking b
INNER JOIN OrderStatus os ON b.status_id = os.id
WHERE os.name IN ('completed', 'paid')
    AND b.booking_date >= DATE '2023-01-01'
ORDER BY "Год", "Месяц";
/

-- 4. Вычисление итогов за период с процентами
WITH MonthlySales AS (
    SELECT 
        TO_CHAR(b.booking_date, 'YYYY-MM') AS "Период",
        SUM(b.total_price) AS "Объем услуг за период",
        COUNT(b.id) AS "Количество услуг"
    FROM Booking b
    INNER JOIN OrderStatus os ON b.status_id = os.id
    WHERE os.name IN ('completed', 'paid')
        AND b.booking_date BETWEEN DATE '2024-01-01' AND DATE '2024-12-31'
    GROUP BY TO_CHAR(b.booking_date, 'YYYY-MM')
),
TotalStats AS (
    SELECT 
        SUM("Объем услуг за период") AS "Общий объем",
        MAX("Объем услуг за период") AS "Максимальный объем"
    FROM MonthlySales
)
SELECT 
    ms."Период",
    ms."Количество услуг",
    ms."Объем услуг за период",
    ts."Общий объем",
    ROUND(ms."Объем услуг за период" * 100 / NULLIF(ts."Общий объем", 0), 2) AS "Процент от общего (%)",
    ts."Максимальный объем",
    ROUND(ms."Объем услуг за период" * 100 / NULLIF(ts."Максимальный объем", 0), 2) AS "Процент от максимума (%)"
FROM MonthlySales ms
CROSS JOIN TotalStats ts
ORDER BY ms."Период";
/


-- 5. ROW_NUMBER() для пагинации (по 20 строк)
SELECT 
    t.id AS "ID",
    t.title AS "Название тура",
    t.base_price AS "Цена (руб.)",
    t.duration_days AS "Длительность (дней)",
    t.departure_date AS "Дата отправления",
    c.name AS "Страна назначения"
FROM Tour t
INNER JOIN Country c ON t.country_id = c.id
WHERE t.is_active = 1
AND ROWNUM <= 20
ORDER BY t.id;
/



-- 6. ROW_NUMBER() для удаления дубликатов
BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE TempOrderStatus PURGE';
EXCEPTION
    WHEN OTHERS THEN NULL;
END;
/

CREATE TABLE TempOrderStatus (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY,
    name NVARCHAR2(50),
    description NVARCHAR2(500),
    is_final NUMBER(1)
);

-- Вставляем данные с дубликатами
INSERT INTO TempOrderStatus (name, description, is_final) VALUES ('pending', 'Ожидание подтверждения', 0);
INSERT INTO TempOrderStatus (name, description, is_final) VALUES ('pending', 'Ожидание подтверждения (ДУБЛИКАТ 1)', 0);
INSERT INTO TempOrderStatus (name, description, is_final) VALUES ('pending', 'Ожидание подтверждения (ДУБЛИКАТ 2)', 0);
INSERT INTO TempOrderStatus (name, description, is_final) VALUES ('confirmed', 'Подтверждено', 0);
INSERT INTO TempOrderStatus (name, description, is_final) VALUES ('confirmed', 'Подтверждено (ДУБЛИКАТ)', 0);
INSERT INTO TempOrderStatus (name, description, is_final) VALUES ('paid', 'Оплачено', 0);
INSERT INTO TempOrderStatus (name, description, is_final) VALUES ('completed', 'Завершено', 1);
INSERT INTO TempOrderStatus (name, description, is_final) VALUES ('cancelled', 'Отменено', 1);
COMMIT;

-- Показываем дубликаты
SELECT name, COUNT(*) AS DuplicateCount
FROM TempOrderStatus
GROUP BY name
HAVING COUNT(*) > 1;

-- Удаляем дубликаты, оставляя самую старую запись (с минимальным id)
DELETE FROM TempOrderStatus
WHERE id IN (
    SELECT id FROM (
        SELECT 
            id,
            name,
            ROW_NUMBER() OVER (PARTITION BY name ORDER BY id) AS RowNum
        FROM TempOrderStatus
    )
    WHERE RowNum > 1
);
COMMIT;

-- Проверяем результат
SELECT name, COUNT(*) AS FinalCount
FROM TempOrderStatus
GROUP BY name
ORDER BY name;

-- Очищаем
DROP TABLE TempOrderStatus PURGE;
/

-- 7. Для каждого клиента - 6 самых посещаемых стран
WITH ClientCountryVisits AS (
    SELECT 
        u.id AS ClientId,
        u.first_name || ' ' || u.last_name AS Клиент,
        c.name AS Страна,
        COUNT(b.id) AS КоличествоПосещений,
        ROW_NUMBER() OVER (PARTITION BY u.id ORDER BY COUNT(b.id) DESC) AS RankInClient
    FROM Booking b
    INNER JOIN Client cl ON b.client_id = cl.user_id
    INNER JOIN "User" u ON cl.user_id = u.id
    INNER JOIN Tour t ON b.tour_id = t.id
    INNER JOIN Country c ON t.country_id = c.id
    INNER JOIN OrderStatus os ON b.status_id = os.id
    WHERE os.name IN ('completed', 'paid')
    GROUP BY u.id, u.first_name, u.last_name, c.name
),
Top6Countries AS (
    SELECT Страна, COUNT(*) AS ОбщаяПопулярность
    FROM ClientCountryVisits
    GROUP BY Страна
    ORDER BY ОбщаяПопулярность DESC
    FETCH FIRST 6 ROWS ONLY
),
AllClients AS (
    SELECT DISTINCT ClientId, Клиент FROM ClientCountryVisits
)
SELECT 
    ac.Клиент AS "Клиент",
    t6.Страна AS "Страна",
    NVL(ccv.КоличествоПосещений, 0) AS "Количество посещений",
    ccv.RankInClient AS "Ранг у клиента",
    t6.ОбщаяПопулярность AS "Общая популярность"
FROM Top6Countries t6
CROSS JOIN AllClients ac
LEFT JOIN ClientCountryVisits ccv ON ccv.ClientId = ac.ClientId AND ccv.Страна = t6.Страна
ORDER BY ac.Клиент, t6.ОбщаяПопулярность DESC;
/


-- 8. Какой маршрут включает наибольшее число достопримечательностей определенного вида
BEGIN
    EXECUTE IMMEDIATE 'CREATE TABLE Attraction (
        id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        name NVARCHAR2(200) NOT NULL,
        type NVARCHAR2(100) NOT NULL,
        country_id NUMBER NOT NULL,
        CONSTRAINT fk_attraction_country FOREIGN KEY (country_id) REFERENCES Country(id)
    )';
EXCEPTION
    WHEN OTHERS THEN NULL;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'CREATE TABLE TourAttraction (
        tour_id NUMBER NOT NULL,
        attraction_id NUMBER NOT NULL,
        CONSTRAINT pk_tourattraction PRIMARY KEY (tour_id, attraction_id),
        CONSTRAINT fk_ta_tour FOREIGN KEY (tour_id) REFERENCES Tour(id),
        CONSTRAINT fk_ta_attraction FOREIGN KEY (attraction_id) REFERENCES Attraction(id)
    )';
EXCEPTION
    WHEN OTHERS THEN NULL;
END;
/

INSERT INTO Attraction (name, type, country_id) VALUES ('Голубая мечеть', 'Религиозный', 1);
INSERT INTO Attraction (name, type, country_id) VALUES ('Айя-София', 'Религиозный', 1);
INSERT INTO Attraction (name, type, country_id) VALUES ('Пирамиды Гизы', 'Древний', 2);
INSERT INTO Attraction (name, type, country_id) VALUES ('Колизей', 'Древний', 3);
INSERT INTO Attraction (name, type, country_id) VALUES ('Ватикан', 'Религиозный', 3);
COMMIT;

INSERT INTO TourAttraction (tour_id, attraction_id) VALUES (1, 1);
INSERT INTO TourAttraction (tour_id, attraction_id) VALUES (1, 2);
INSERT INTO TourAttraction (tour_id, attraction_id) VALUES (2, 3);
INSERT INTO TourAttraction (tour_id, attraction_id) VALUES (3, 4);
INSERT INTO TourAttraction (tour_id, attraction_id) VALUES (3, 5);
COMMIT;

WITH AttractionCount AS (
    SELECT 
        a.type AS "Вид достопримечательностей",
        t.id AS TourId,
        t.title AS "Маршрут",
        COUNT(*) AS "Количество",
        RANK() OVER (PARTITION BY a.type ORDER BY COUNT(*) DESC) AS RankInType
    FROM Attraction a
    INNER JOIN TourAttraction ta ON a.id = ta.attraction_id
    INNER JOIN Tour t ON ta.tour_id = t.id
    GROUP BY a.type, t.id, t.title
)
SELECT 
    "Вид достопримечательностей",
    "Маршрут",
    "Количество",
    RankInType AS "Ранг в категории"
FROM AttractionCount
WHERE RankInType = 1
ORDER BY "Вид достопримечательностей";
/