
CREATE USER RMV_LAB04 IDENTIFIED BY "12345"
DEFAULT TABLESPACE USERS
TEMPORARY TABLESPACE TEMP
QUOTA 100M ON USERS;

GRANT CREATE SESSION, CREATE TABLE, CREATE SEQUENCE TO RMV_LAB04;
GRANT UNLIMITED TABLESPACE TO RMV_LAB04;

SELECT username, account_status FROM dba_users WHERE username LIKE 'RMV%';