GRANT CREATE TRIGGER, DROP ANY TRIGGER TO RMV;

ALTER SESSION SET NLS_DATE_FORMAT='dd-mm-yyyy hh24:mi:ss';



-- Задание 1
CREATE TABLE Task_Table
(
    a INT PRIMARY KEY,
    b VARCHAR(30)
);

-- Задание 2
BEGIN
    FOR i IN 1..10 LOOP
        INSERT INTO Task_Table VALUES (i, 'a');
    END LOOP;
    COMMIT;
END;
/

-- Задание 3-4
CREATE OR REPLACE TRIGGER INSERT_TR_BEFORE_STATEMENT
    BEFORE INSERT ON Task_Table
BEGIN
    DBMS_OUTPUT.PUT_LINE('INSERT_TR_BEFORE_STATEMENT');
END;
/

CREATE OR REPLACE TRIGGER UPDATE_TR_BEFORE_STATEMENT
    BEFORE UPDATE ON Task_Table
BEGIN
    DBMS_OUTPUT.PUT_LINE('UPDATE_TR_BEFORE_STATEMENT');
END;
/

CREATE OR REPLACE TRIGGER DELETE_TR_BEFORE_STATEMENT
    BEFORE DELETE ON Task_Table
BEGIN
    DBMS_OUTPUT.PUT_LINE('DELETE_TR_BEFORE_STATEMENT');
END;
/

-- Задание 5
CREATE OR REPLACE TRIGGER INSERT_TR_BEFORE_ROW
    BEFORE INSERT ON Task_Table
    FOR EACH ROW
BEGIN
    DBMS_OUTPUT.PUT_LINE('INSERT_TR_BEFORE_ROW');
END;
/

CREATE OR REPLACE TRIGGER UPDATE_TR_BEFORE_ROW
    BEFORE UPDATE ON Task_Table
    FOR EACH ROW
BEGIN
    DBMS_OUTPUT.PUT_LINE('UPDATE_TR_BEFORE_ROW');
END;
/

CREATE OR REPLACE TRIGGER DELETE_TR_BEFORE_ROW
    BEFORE DELETE ON Task_Table
    FOR EACH ROW
BEGIN
    DBMS_OUTPUT.PUT_LINE('DELETE_TR_BEFORE_ROW');
END;
/

-- Задание 6
CREATE OR REPLACE TRIGGER TRIGGER_DML
    BEFORE INSERT OR UPDATE OR DELETE ON Task_Table
BEGIN
    IF INSERTING THEN
        DBMS_OUTPUT.PUT_LINE('TRIGGER_DML_BEFORE_INSERT');
    ELSIF UPDATING THEN
        DBMS_OUTPUT.PUT_LINE('TRIGGER_DML_BEFORE_UPDATE');
    ELSIF DELETING THEN
        DBMS_OUTPUT.PUT_LINE('TRIGGER_DML_BEFORE_DELETE');
    END IF;
END;
/

-- Задание 7
CREATE OR REPLACE TRIGGER INSERT_TR_AFTER_STATEMENT
    AFTER INSERT ON Task_Table
BEGIN
    DBMS_OUTPUT.PUT_LINE('INSERT_TR_AFTER_STATEMENT');
END;
/

CREATE OR REPLACE TRIGGER UPDATE_TR_AFTER_STATEMENT
    AFTER UPDATE ON Task_Table
BEGIN
    DBMS_OUTPUT.PUT_LINE('UPDATE_TR_AFTER_STATEMENT');
END;
/

CREATE OR REPLACE TRIGGER DELETE_TR_AFTER_STATEMENT
    AFTER DELETE ON Task_Table
BEGIN
    DBMS_OUTPUT.PUT_LINE('DELETE_TR_AFTER_STATEMENT');
END;
/

-- Задание 8
CREATE OR REPLACE TRIGGER INSERT_TR_AFTER_ROW
    AFTER INSERT ON Task_Table
    FOR EACH ROW
BEGIN
    DBMS_OUTPUT.PUT_LINE('INSERT_TR_AFTER_ROW');
END;
/

CREATE OR REPLACE TRIGGER UPDATE_TR_AFTER_ROW
    AFTER UPDATE ON Task_Table
    FOR EACH ROW
BEGIN
    DBMS_OUTPUT.PUT_LINE('UPDATE_TR_AFTER_ROW');
END;
/

CREATE OR REPLACE TRIGGER DELETE_TR_AFTER_ROW
    AFTER DELETE ON Task_Table
    FOR EACH ROW
BEGIN
    DBMS_OUTPUT.PUT_LINE('DELETE_TR_AFTER_ROW');
END;
/

-- Задание 9
CREATE TABLE AUDITS
(
    OperationDate DATE,
    OperationType VARCHAR2(50),
    TriggerName   VARCHAR2(50),
    Data          VARCHAR2(100)
);

-- Задание 10
CREATE OR REPLACE TRIGGER TRIGGER_BEFORE_AUDIT
    BEFORE INSERT OR UPDATE OR DELETE ON Task_Table
    FOR EACH ROW
BEGIN
    IF INSERTING THEN
        DBMS_OUTPUT.PUT_LINE('TRIGGER_BEFORE_AUDIT - INSERT');
        INSERT INTO AUDITS VALUES (SYSDATE, 'insert', 'TRIGGER_BEFORE_AUDIT', :NEW.a || ' ' || :NEW.b);
    ELSIF UPDATING THEN
        DBMS_OUTPUT.PUT_LINE('TRIGGER_BEFORE_AUDIT - UPDATE');
        INSERT INTO AUDITS VALUES (SYSDATE, 'update', 'TRIGGER_BEFORE_AUDIT', :OLD.a || ' ' || :OLD.b || ' -> ' || :NEW.a || ' ' || :NEW.b);
    ELSIF DELETING THEN
        DBMS_OUTPUT.PUT_LINE('TRIGGER_BEFORE_AUDIT - DELETE');
        INSERT INTO AUDITS VALUES (SYSDATE, 'delete', 'TRIGGER_BEFORE_AUDIT', :OLD.a || ' ' || :OLD.b);
    END IF;
END;
/

CREATE OR REPLACE TRIGGER TRIGGER_AFTER_AUDIT
    AFTER INSERT OR UPDATE OR DELETE ON Task_Table
    FOR EACH ROW
BEGIN
    IF INSERTING THEN
        DBMS_OUTPUT.PUT_LINE('TRIGGER_AFTER_AUDIT - INSERT');
        INSERT INTO AUDITS VALUES (SYSDATE, 'insert', 'TRIGGER_AFTER_AUDIT', :NEW.a || ' ' || :NEW.b);
    ELSIF UPDATING THEN
        DBMS_OUTPUT.PUT_LINE('TRIGGER_AFTER_AUDIT - UPDATE');
        INSERT INTO AUDITS VALUES (SYSDATE, 'update', 'TRIGGER_AFTER_AUDIT', :OLD.a || ' ' || :OLD.b || ' -> ' || :NEW.a || ' ' || :NEW.b);
    ELSIF DELETING THEN
        DBMS_OUTPUT.PUT_LINE('TRIGGER_AFTER_AUDIT - DELETE');
        INSERT INTO AUDITS VALUES (SYSDATE, 'delete', 'TRIGGER_AFTER_AUDIT', :OLD.a || ' ' || :OLD.b);
    END IF;
END;
/

-- Задание 11
SET SERVEROUTPUT ON;
BEGIN
    DBMS_OUTPUT.PUT_LINE('=== Тест нарушения целостности по PK ===');
    INSERT INTO Task_Table VALUES (1, 'v');
EXCEPTION
    WHEN DUP_VAL_ON_INDEX THEN
        DBMS_OUTPUT.PUT_LINE('Ошибка: дублирование первичного ключа - триггеры BEFORE сработали, но транзакция откатилась');
END;
/

-- Задание 12
CREATE OR REPLACE TRIGGER TRIGGER_PREVENT_TABLE_DROP
    BEFORE DROP ON RMV.SCHEMA
BEGIN
    IF DICTIONARY_OBJ_NAME = 'TASK_TABLE' THEN
        RAISE_APPLICATION_ERROR(-20000, 'You can not drop table TASK_TABLE.');
    END IF;
END;
/

-- Задание 13
BEGIN
    DBMS_OUTPUT.PUT_LINE('=== Пробуем удалить AUDITS ===');
    EXECUTE IMMEDIATE 'DROP TABLE AUDITS';
    DBMS_OUTPUT.PUT_LINE('Таблица AUDITS удалена успешно');
    
    DBMS_OUTPUT.PUT_LINE('=== Пробуем удалить Task_Table ===');
    EXECUTE IMMEDIATE 'DROP TABLE Task_Table';
EXCEPTION
    WHEN OTHERS THEN
        DBMS_OUTPUT.PUT_LINE('Ошибка при удалении Task_Table: ' || SQLERRM);
        DBMS_OUTPUT.PUT_LINE('Триггер предотвратил удаление таблицы');
END;
/

CREATE TABLE AUDITS
(
    OperationDate DATE,
    OperationType VARCHAR2(50),
    TriggerName   VARCHAR2(50),
    Data          VARCHAR2(100)
);

-- Задание 14
CREATE OR REPLACE VIEW TASK_TABLE_VIEW AS SELECT * FROM TASK_TABLE;

CREATE OR REPLACE TRIGGER TRIGGER_INSTEAD_OF_INSERT
    INSTEAD OF INSERT ON TASK_TABLE_VIEW
    FOR EACH ROW
BEGIN
    DBMS_OUTPUT.PUT_LINE('TRIGGER_INSTEAD_OF_INSERT сработал');
    INSERT INTO TASK_TABLE VALUES (100, 'www');
END;
/

-- Демонстрация
BEGIN
    DBMS_OUTPUT.PUT_LINE('=== Очищаем таблицу для теста ===');
    DELETE FROM Task_Table;
    COMMIT;
    
    DBMS_OUTPUT.PUT_LINE('=== Вставляем тестовые данные ===');
    INSERT INTO Task_Table VALUES (1, 'test1');
    INSERT INTO Task_Table VALUES (2, 'test2');
    INSERT INTO Task_Table VALUES (3, 'test3');
    COMMIT;
    
    DBMS_OUTPUT.PUT_LINE('=== Демонстрация порядка триггеров при INSERT ===');
    INSERT INTO Task_Table VALUES (10, 'new_row');
    
    DBMS_OUTPUT.PUT_LINE('=== Демонстрация порядка триггеров при UPDATE ===');
    UPDATE Task_Table SET b = 'updated' WHERE a = 1;
    
    DBMS_OUTPUT.PUT_LINE('=== Демонстрация порядка триггеров при DELETE ===');
    DELETE FROM Task_Table WHERE a = 2;
    
    DBMS_OUTPUT.PUT_LINE('=== Демонстрация INSTEAD OF триггера ===');
    INSERT INTO TASK_TABLE_VIEW VALUES (111, 'eee');
    
    DBMS_OUTPUT.PUT_LINE('=== Проверяем таблицы ===');
END;
/

SELECT 'Task_Table данные:' FROM dual;
SELECT * FROM Task_Table ORDER BY a;

SELECT 'AUDITS записи:' FROM dual;
SELECT * FROM AUDITS ORDER BY OperationDate;












-- Очистка
BEGIN
    -- Удаляем триггеры
    FOR trg IN (SELECT trigger_name FROM user_triggers) LOOP
        BEGIN
            EXECUTE IMMEDIATE 'DROP TRIGGER ' || trg.trigger_name;
        EXCEPTION
            WHEN OTHERS THEN NULL;
        END;
    END LOOP;
    
    -- Удаляем представления
    FOR vw IN (SELECT view_name FROM user_views) LOOP
        BEGIN
            EXECUTE IMMEDIATE 'DROP VIEW ' || vw.view_name;
        EXCEPTION
            WHEN OTHERS THEN NULL;
        END;
    END LOOP;
    
    -- Удаляем таблицы
    BEGIN
        EXECUTE IMMEDIATE 'DROP TABLE AUDITS';
    EXCEPTION
        WHEN OTHERS THEN NULL;
    END;
    
    BEGIN
        EXECUTE IMMEDIATE 'DROP TABLE Task_Table';
    EXCEPTION
        WHEN OTHERS THEN NULL;
    END;
    
    COMMIT;
    DBMS_OUTPUT.PUT_LINE('Очистка завершена');
END;
/



