events {
    worker_connections 1024;
}

stream {
    upstream sqlserver {
        server host.docker.internal:10443;
    }
    
    server {
        listen 1433;
        proxy_pass sqlserver;
        proxy_connect_timeout 30s;
        proxy_timeout 600s;
    }
}