ALTER SESSION SET "_ORACLE_SCRIPT" = TRUE;


----№1
DROP TABLESPACE TS_RMV INCLUDING CONTENTS AND DATAFILES CASCADE CONSTRAINTS;

CREATE TABLESPACE TS_RMV
  DATAFILE '/opt/oracle/oradata/XE/XEPDB1/TS_RMV_01.dbf'
  SIZE 7M
  AUTOEXTEND ON NEXT 5M
  MAXSIZE 20M;

----№2
DROP TABLESPACE TS_RMV_TEMP INCLUDING CONTENTS AND DATAFILES CASCADE CONSTRAINTS;

CREATE TEMPORARY TABLESPACE TS_RMV_TEMP
  TEMPFILE '/opt/oracle/oradata/XE/XEPDB1/TS_RMV_TEMP_01.dbf'
  SIZE 5M
  AUTOEXTEND ON NEXT 3M
  MAXSIZE 30M;

----№3
SELECT * FROM SYS.dba_tablespaces;
SELECT * FROM SYS.dba_data_files;

----№4
--ALTER SESSION SET "_ORACLE_SCRIPT"=TRUE;

DROP ROLE RL_RMVCORE;

CREATE ROLE RL_RMVCORE;

GRANT CONNECT, CREATE SESSION, CREATE ANY TABLE, DROP ANY TABLE, CREATE ANY VIEW,
DROP ANY VIEW, CREATE ANY PROCEDURE, DROP ANY PROCEDURE TO RL_RMVCORE;


REVOKE CONNECT, CREATE SESSION, CREATE ANY TABLE, DROP ANY TABLE, 
        CREATE ANY VIEW, DROP ANY VIEW, CREATE ANY PROCEDURE, DROP ANY PROCEDURE 
FROM RL_RMVCORE;



----№5
SELECT * FROM dba_roles WHERE ROLE LIKE '%RL%';
SELECT * FROM dba_sys_privs WHERE GRANTEE = 'RL_RMVCORE';

----№6

DROP PROFILE PF_RMVCORE CASCADE;

CREATE PROFILE PF_RMVCORE LIMIT
  PASSWORD_LIFE_TIME 365
  SESSIONS_PER_USER 5
  FAILED_LOGIN_ATTEMPTS 5
  PASSWORD_LOCK_TIME 1
  PASSWORD_REUSE_TIME 10
  PASSWORD_GRACE_TIME DEFAULT
  CONNECT_TIME 180
  IDLE_TIME 45;

----№7
SELECT PROFILE, RESOURCE_NAME, LIMIT FROM dba_profiles ORDER BY PROFILE;
SELECT PROFILE, RESOURCE_NAME, LIMIT FROM dba_profiles WHERE PROFILE = 'PF_RMVCORE';
SELECT PROFILE, RESOURCE_NAME, LIMIT FROM dba_profiles WHERE PROFILE = 'DEFAULT';

----№8

DROP USER RMVCORE CASCADE;

CREATE USER RMVCORE IDENTIFIED BY 12345
DEFAULT TABLESPACE TS_RMV QUOTA UNLIMITED ON TS_RMV
TEMPORARY TABLESPACE TS_RMV_TEMP
PROFILE PF_RMVCORE
ACCOUNT UNLOCK
PASSWORD EXPIRE;

GRANT RL_RMVCORE TO RMVCORE;




----№11
DROP TABLESPACE RMV_QDATA INCLUDING CONTENTS AND DATAFILES CASCADE CONSTRAINTS;

CREATE TABLESPACE RMV_QDATA
  DATAFILE '/opt/oracle/oradata/XE/XEPDB1/RMV_QDATA_01.dbf'
  SIZE 10M
  OFFLINE;

SELECT TABLESPACE_NAME, STATUS, CONTENTS FROM SYS.dba_tablespaces;

ALTER TABLESPACE RMV_QDATA ONLINE;

ALTER USER RMVCORE QUOTA 2M ON RMV_QDATA;











-------------------------
ALTER USER RMVCORE IDENTIFIED BY NewPassword123;

SELECT username, account_status FROM dba_users WHERE username = 'RMVCORE';
-----------------------------------------------------------------

