---- задание 1
CREATE TABLE Report (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    xml_data XMLTYPE NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);


---- задание 2
CREATE OR REPLACE PROCEDURE sp_GenerateTourReportXML (
    p_StartDate IN DATE,
    p_EndDate IN DATE,
    p_xml_result OUT XMLTYPE
)
IS
BEGIN
    SELECT XMLELEMENT("ToursReport",
        XMLATTRIBUTES(
            CURRENT_TIMESTAMP AS "ReportGenerated",
            TO_CHAR(p_StartDate, 'YYYY-MM-DD') AS "StartDate",
            TO_CHAR(p_EndDate, 'YYYY-MM-DD') AS "EndDate"
        ),
        XMLAGG(
            XMLELEMENT("Tour",
                XMLATTRIBUTES(t.id AS "id"),
                XMLELEMENT("Name", t.title),
                XMLELEMENT("Country", c.name),
                XMLELEMENT("Hotel", h.name),
                XMLELEMENT("Stars", h.stars),
                XMLELEMENT("DepartureDate", TO_CHAR(t.departure_date, 'YYYY-MM-DD')),
                XMLELEMENT("BasePrice", t.base_price),
                XMLELEMENT("BookingsCount", NVL(b.BookingCount, 0)),
                XMLELEMENT("TotalRevenue", NVL(b.TotalRevenue, 0)),
                XMLELEMENT("AverageCheck", ROUND(NVL(b.AvgCheck, 0), 2))
            )
        )
    )
    INTO p_xml_result
    FROM Tour t
    INNER JOIN Country c ON t.country_id = c.id
    INNER JOIN Hotel h ON t.hotel_id = h.id
    LEFT JOIN (
        SELECT 
            tour_id,
            COUNT(*) AS BookingCount,
            SUM(total_price) AS TotalRevenue,
            AVG(total_price) AS AvgCheck
        FROM Booking
        GROUP BY tour_id
    ) b ON t.id = b.tour_id
    WHERE t.departure_date BETWEEN p_StartDate AND p_EndDate;
END sp_GenerateTourReportXML;
/

-- Проверка
DECLARE
    v_xml XMLTYPE;
BEGIN
    sp_GenerateTourReportXML(
        TO_DATE('2024-01-01', 'YYYY-MM-DD'),
        TO_DATE('2024-12-31', 'YYYY-MM-DD'),
        v_xml
    );
    DBMS_OUTPUT.PUT_LINE(v_xml.getClobVal());
END;
/



---- задание 3
CREATE OR REPLACE PROCEDURE sp_InsertXMLReport (
    p_StartDate IN DATE,
    p_EndDate IN DATE,
    p_new_id OUT NUMBER
)
IS
    v_xml XMLTYPE;
BEGIN
    sp_GenerateTourReportXML(p_StartDate, p_EndDate, v_xml);

    INSERT INTO Report (xml_data)
    VALUES (v_xml)
    RETURNING id INTO p_new_id;
    
    COMMIT;
    
    DBMS_OUTPUT.PUT_LINE('Report inserted with ID: ' || p_new_id);
END sp_InsertXMLReport;
/

-- Проверка
DECLARE
    v_id NUMBER;
BEGIN
    sp_InsertXMLReport(
        TO_DATE('2024-01-01', 'YYYY-MM-DD'),
        TO_DATE('2024-12-31', 'YYYY-MM-DD'),
        v_id
    );
END;
/



---- задание 4
CREATE INDEX IX_Report_XMLData ON Report(xml_data) INDEXTYPE IS XDB.XMLINDEX;

SELECT index_name, index_type FROM user_indexes WHERE table_name = 'REPORT';


---- задание 5
CREATE OR REPLACE PROCEDURE sp_ExtractXMLValue (
    p_TourName IN VARCHAR2 DEFAULT NULL,
    p_MinRevenue IN NUMBER DEFAULT NULL,
    p_results OUT SYS_REFCURSOR
)
IS
BEGIN
    OPEN p_results FOR
        SELECT 
            r.id AS ReportID,
            r.created_at,
            EXTRACTVALUE(VALUE(t), '/Tour/Name') AS TourName,
            EXTRACTVALUE(VALUE(t), '/Tour/Country') AS Country,
            EXTRACTVALUE(VALUE(t), '/Tour/Hotel') AS Hotel,
            TO_NUMBER(EXTRACTVALUE(VALUE(t), '/Tour/Stars')) AS Stars,
            EXTRACTVALUE(VALUE(t), '/Tour/DepartureDate') AS DepartureDate,
            TO_NUMBER(EXTRACTVALUE(VALUE(t), '/Tour/BasePrice')) AS BasePrice,
            TO_NUMBER(EXTRACTVALUE(VALUE(t), '/Tour/BookingsCount')) AS BookingsCount,
            TO_NUMBER(EXTRACTVALUE(VALUE(t), '/Tour/TotalRevenue')) AS TotalRevenue,
            TO_NUMBER(EXTRACTVALUE(VALUE(t), '/Tour/AverageCheck')) AS AverageCheck
        FROM Report r,
             TABLE(XMLSEQUENCE(EXTRACT(r.xml_data, '/ToursReport/Tour'))) t
        WHERE (p_TourName IS NULL OR UPPER(EXTRACTVALUE(VALUE(t), '/Tour/Name')) LIKE '%' || UPPER(p_TourName) || '%')
          AND (p_MinRevenue IS NULL OR TO_NUMBER(EXTRACTVALUE(VALUE(t), '/Tour/TotalRevenue')) >= p_MinRevenue)
        ORDER BY r.id, TotalRevenue DESC;
END sp_ExtractXMLValue;
/


DECLARE
    v_cursor SYS_REFCURSOR;
    v_ReportID NUMBER;
    v_CreatedAt TIMESTAMP;
    v_TourName VARCHAR2(255);
    v_Country VARCHAR2(100);
    v_Hotel VARCHAR2(200);
    v_Stars NUMBER;
    v_DepartureDate VARCHAR2(10);
    v_BasePrice NUMBER;
    v_BookingsCount NUMBER;
    v_TotalRevenue NUMBER;
    v_AverageCheck NUMBER;
BEGIN
    sp_ExtractXMLValue(NULL, NULL, v_cursor);
    
    DBMS_OUTPUT.PUT_LINE('=== TOUR REPORT ===');
    LOOP
        FETCH v_cursor INTO v_ReportID, v_CreatedAt, v_TourName, v_Country, 
                           v_Hotel, v_Stars, v_DepartureDate, v_BasePrice,
                           v_BookingsCount, v_TotalRevenue, v_AverageCheck;
        EXIT WHEN v_cursor%NOTFOUND;
        DBMS_OUTPUT.PUT_LINE('Tour: ' || v_TourName || ' | Country: ' || v_Country || 
                             ' | Bookings: ' || v_BookingsCount || ' | Revenue: ' || v_TotalRevenue);
    END LOOP;
    CLOSE v_cursor;
END;
/

DECLARE
    v_cursor SYS_REFCURSOR;
    v_ReportID NUMBER;
    v_CreatedAt TIMESTAMP;
    v_TourName VARCHAR2(255);
    v_Country VARCHAR2(100);
    v_Hotel VARCHAR2(200);
    v_Stars NUMBER;
    v_DepartureDate VARCHAR2(10);
    v_BasePrice NUMBER;
    v_BookingsCount NUMBER;
    v_TotalRevenue NUMBER;
    v_AverageCheck NUMBER;
BEGIN
    sp_ExtractXMLValue('Анталья', NULL, v_cursor);
    
    DBMS_OUTPUT.PUT_LINE('=== TOURS WITH "Анталья" ===');
    LOOP
        FETCH v_cursor INTO v_ReportID, v_CreatedAt, v_TourName, v_Country, 
                           v_Hotel, v_Stars, v_DepartureDate, v_BasePrice,
                           v_BookingsCount, v_TotalRevenue, v_AverageCheck;
        EXIT WHEN v_cursor%NOTFOUND;
        DBMS_OUTPUT.PUT_LINE('Tour: ' || v_TourName || ' | Revenue: ' || v_TotalRevenue);
    END LOOP;
    CLOSE v_cursor;
END;
/

DECLARE
    v_cursor SYS_REFCURSOR;
    v_ReportID NUMBER;
    v_CreatedAt TIMESTAMP;
    v_TourName VARCHAR2(255);
    v_Country VARCHAR2(100);
    v_Hotel VARCHAR2(200);
    v_Stars NUMBER;
    v_DepartureDate VARCHAR2(10);
    v_BasePrice NUMBER;
    v_BookingsCount NUMBER;
    v_TotalRevenue NUMBER;
    v_AverageCheck NUMBER;
BEGIN
    sp_ExtractXMLValue(NULL, 5000, v_cursor);
    
    DBMS_OUTPUT.PUT_LINE('=== TOURS WITH REVENUE > 5000 ===');
    LOOP
        FETCH v_cursor INTO v_ReportID, v_CreatedAt, v_TourName, v_Country, 
                           v_Hotel, v_Stars, v_DepartureDate, v_BasePrice,
                           v_BookingsCount, v_TotalRevenue, v_AverageCheck;
        EXIT WHEN v_cursor%NOTFOUND;
        DBMS_OUTPUT.PUT_LINE('Tour: ' || v_TourName || ' | Revenue: ' || v_TotalRevenue);
    END LOOP;
    CLOSE v_cursor;
END;
/


----очистка
DROP INDEX IX_Report_XMLData;

TRUNCATE TABLE Report;

DROP TABLE Report;






