-- как RMV
DROP MATERIALIZED VIEW MV;
DROP VIEW V1;
DROP TABLE TASK_B;
DROP TABLE TASK_A;

DROP SYNONYM SYNONYM_C;
DROP TABLE C;
DROP TABLE B;
DROP TABLE A;
DROP CLUSTER ABC;
DROP TABLE T1;
DROP SEQUENCE S4;
DROP SEQUENCE S3;
DROP SEQUENCE S2;
DROP SEQUENCE S1;



-- как SYS
DROP PUBLIC SYNONYM SYNONYM_B;
REVOKE EXECUTE ON DBMS_MVIEW FROM RMV;
REVOKE SELECT ON SYS.DBA_TABLES FROM RMV;
REVOKE SELECT ON SYS.DBA_CLUSTERS FROM RMV;
REVOKE CREATE MATERIALIZED VIEW FROM RMV;
REVOKE CREATE PUBLIC SYNONYM FROM RMV;
REVOKE CREATE SYNONYM FROM RMV;
REVOKE CREATE CLUSTER FROM RMV;
REVOKE CREATE SEQUENCE FROM RMV;
REVOKE CREATE VIEW FROM RMV;
REVOKE CREATE TABLE FROM RMV;
REVOKE CREATE SESSION FROM RMV;
DROP USER RMV CASCADE;

-- как SYS - проверка удаления пользователя
SELECT USERNAME FROM DBA_USERS WHERE USERNAME = 'RMV';

-- как SYS - проверка публичных синонимов
SELECT SYNONYM_NAME FROM DBA_SYNONYMS WHERE OWNER = 'PUBLIC' AND SYNONYM_NAME = 'SYNONYM_B';



-- как RMV - проверка удаления объектов
SELECT 'SEQUENCES' AS OBJECT_TYPE, COUNT(*) AS COUNT FROM USER_SEQUENCES
UNION ALL
SELECT 'TABLES', COUNT(*) FROM USER_TABLES
UNION ALL
SELECT 'CLUSTERS', COUNT(*) FROM USER_CLUSTERS
UNION ALL
SELECT 'SYNONYMS', COUNT(*) FROM USER_SYNONYMS
UNION ALL
SELECT 'VIEWS', COUNT(*) FROM USER_VIEWS
UNION ALL
SELECT 'MATERIALIZED VIEWS', COUNT(*) FROM USER_MVIEWS;