-- как SYS
CREATE USER RMV IDENTIFIED BY "MyStrongPassw0rd"
DEFAULT TABLESPACE USERS
TEMPORARY TABLESPACE TEMP
QUOTA UNLIMITED ON USERS;

GRANT CREATE SESSION TO RMV;
GRANT CREATE TABLE TO RMV;
GRANT CREATE SEQUENCE TO RMV;
GRANT CREATE CLUSTER TO RMV;
GRANT CREATE VIEW TO RMV;
GRANT CREATE MATERIALIZED VIEW TO RMV;
GRANT CREATE SYNONYM TO RMV;


-- как RMV_USER
-- Задание 2
--DROP SEQUENCE S1;

CREATE SEQUENCE S1
    INCREMENT BY 10
    START WITH 1000
    NOMAXVALUE
    NOMINVALUE
    NOCYCLE
    NOCACHE
    NOORDER;

SELECT S1.NEXTVAL FROM DUAL;
SELECT S1.NEXTVAL FROM DUAL;
SELECT S1.NEXTVAL FROM DUAL;

SELECT S1.CURRVAL FROM DUAL;

-- Задание 3
--DROP SEQUENCE S2;

CREATE SEQUENCE S2
    START WITH 10
    INCREMENT BY 10
    MAXVALUE 100
    NOCYCLE;

SELECT S2.NEXTVAL FROM DUAL;
SELECT S2.CURRVAL FROM DUAL;

-- Задание 4
--DROP SEQUENCE S3;

CREATE SEQUENCE S3
    START WITH 10
    INCREMENT BY -10
    MINVALUE -100
    MAXVALUE 10
    NOCYCLE
    ORDER;

SELECT S3.NEXTVAL FROM DUAL;
SELECT S3.CURRVAL FROM DUAL;

-- Задание 5
--DROP SEQUENCE S4;

CREATE SEQUENCE S4
    START WITH 1
    INCREMENT BY 1
    MINVALUE 1
    MAXVALUE 10
    CYCLE
    CACHE 5
    NOORDER;

SELECT S4.NEXTVAL FROM DUAL CONNECT BY LEVEL <= 15;

SELECT S4.NEXTVAL FROM DUAL;
SELECT S4.CURRVAL FROM DUAL;

-- Задание 6
SELECT SEQUENCE_NAME, MIN_VALUE, MAX_VALUE, INCREMENT_BY, CYCLE_FLAG, CACHE_SIZE
FROM USER_SEQUENCES;


-- Задание 7
--DROP TABLE T1;

CREATE TABLE T1
(
    N1 NUMBER(20),
    N2 NUMBER(20),
    N3 NUMBER(20),
    N4 NUMBER(20)
) CACHE STORAGE(BUFFER_POOL KEEP);

BEGIN
    FOR i IN 1..7 LOOP
        INSERT INTO T1 (N1, N2, N3, N4)
        VALUES (S1.NEXTVAL, S2.NEXTVAL, S3.NEXTVAL, S4.NEXTVAL);
    END LOOP;
    COMMIT;
END;
/

SELECT * FROM T1;


-- Задание 8
--DROP CLUSTER ABC;

CREATE CLUSTER ABC
(
    X NUMBER(10),
    V VARCHAR2(12)
)
HASHKEYS 200;


-- Задание 9
--DROP TABLE A;

CREATE TABLE A
(
    XA NUMBER(10),
    VA VARCHAR2(12),
    EXTRA_COL VARCHAR2(50)
) CLUSTER ABC (XA, VA);


-- Задание 10
--DROP TABLE B;

CREATE TABLE B
(
    XB NUMBER(10),
    VB VARCHAR2(12),
    EXTRA_COL VARCHAR2(50)
) CLUSTER ABC (XB, VB);


-- Задание 11
--DROP TABLE C;

CREATE TABLE C
(
    XC NUMBER(10),
    VC VARCHAR2(12),
    EXTRA_COL VARCHAR2(50)
) CLUSTER ABC (XC, VC);


-- Задание 12

SELECT CLUSTER_NAME, TABLESPACE_NAME, CLUSTER_TYPE 
FROM USER_CLUSTERS;

SELECT TABLE_NAME, CLUSTER_NAME 
FROM USER_TABLES 
WHERE CLUSTER_NAME = 'ABC';


-- Задание 13
--DROP SYNONYM SYNONYM_C;

CREATE SYNONYM SYNONYM_C FOR C;

INSERT INTO SYNONYM_C VALUES (1, 'test_c', 'extra data');
SELECT * FROM SYNONYM_C;


-- Задание 14
--DROP PUBLIC SYNONYM SYNONYM_B;

CREATE PUBLIC SYNONYM SYNONYM_B FOR RMV.B;

-- SELECT * FROM SYNONYM_B;


-- Задание 15
--DROP TABLE TASK_A CASCADE CONSTRAINTS;
--DROP TABLE TASK_B CASCADE CONSTRAINTS;

CREATE TABLE TASK_A
(
    X NUMBER(20) PRIMARY KEY,
    NAME VARCHAR2(50)
);

CREATE TABLE TASK_B
(
    Y NUMBER(20) PRIMARY KEY,
    A_REF NUMBER(20),
    DESCRIPTION VARCHAR2(50),
    CONSTRAINT FK_TASK_B FOREIGN KEY (A_REF) REFERENCES TASK_A(X)
);

INSERT INTO TASK_A VALUES (1, 'First');
INSERT INTO TASK_A VALUES (2, 'Second');
INSERT INTO TASK_B VALUES (1, 1, 'Reference to First');
INSERT INTO TASK_B VALUES (2, 2, 'Reference to Second');
COMMIT;

--DROP VIEW V1;

CREATE VIEW V1 AS
SELECT A.X, A.NAME, B.Y, B.DESCRIPTION
FROM TASK_A A
INNER JOIN TASK_B B ON A.X = B.A_REF;

SELECT * FROM V1;


-- Задание 16
--DROP MATERIALIZED VIEW MV;

CREATE MATERIALIZED VIEW MV
REFRESH COMPLETE 
START WITH SYSDATE NEXT SYSDATE + INTERVAL '1' MINUTE
AS
SELECT A.X, A.NAME, B.Y, B.DESCRIPTION
FROM TASK_A A
FULL JOIN TASK_B B ON A.X = B.A_REF;

SELECT * FROM MV;

INSERT INTO TASK_A VALUES (3, 'Third');
COMMIT;

EXEC DBMS_MVIEW.REFRESH('MV');

SELECT * FROM MV;









