-- Создание базы данных (раскомментируйте если нужно создать заново)
-- CREATE DATABASE RMV;
-- GO

USE RMV;
GO

-- Удаление существующих таблиц (если нужно пересоздать)
-- Порядок важен из-за внешних ключей
IF OBJECT_ID('AUDITORIUM', 'U') IS NOT NULL DROP TABLE AUDITORIUM;
IF OBJECT_ID('AUDITORIUM_TYPE', 'U') IS NOT NULL DROP TABLE AUDITORIUM_TYPE;
IF OBJECT_ID('SUBJECT', 'U') IS NOT NULL DROP TABLE SUBJECT;
IF OBJECT_ID('TEACHER', 'U') IS NOT NULL DROP TABLE TEACHER;
IF OBJECT_ID('PULPIT', 'U') IS NOT NULL DROP TABLE PULPIT;
IF OBJECT_ID('FACULTY', 'U') IS NOT NULL DROP TABLE FACULTY;
GO

-- Создание таблицы FACULTY (факультеты)
CREATE TABLE FACULTY
(
    FACULTY INT PRIMARY KEY,
    FACULTY_NAME NVARCHAR(30)  -- Используем NVARCHAR вместо NCHAR
);
GO

-- Создание таблицы PULPIT (кафедры)
CREATE TABLE PULPIT
(
    PULPIT INT PRIMARY KEY,
    PULPIT_NAME NVARCHAR(30),  -- Используем NVARCHAR вместо NCHAR
    FACULTY INT,
    CONSTRAINT FK_Pulpits_Facultys FOREIGN KEY (FACULTY) REFERENCES FACULTY(FACULTY)
);
GO

-- Создание таблицы TEACHER (преподаватели)
CREATE TABLE TEACHER
(
    TEACHER INT PRIMARY KEY,
    TEACHER_NAME NVARCHAR(30),  -- Используем NVARCHAR вместо NCHAR
    PULPIT INT,
    CONSTRAINT FK_Teachers_Pulpits FOREIGN KEY (PULPIT) REFERENCES PULPIT(PULPIT)
);
GO

-- Создание таблицы SUBJECT (дисциплины)
CREATE TABLE SUBJECT
(
    SUBJECT INT PRIMARY KEY,
    SUBJECT_NAME NVARCHAR(30),  -- Используем NVARCHAR вместо NCHAR
    PULPIT INT,
    CONSTRAINT FK_Subjects_Pulpits FOREIGN KEY (PULPIT) REFERENCES PULPIT(PULPIT)
);
GO

-- Создание таблицы AUDITORIUM_TYPE (типы аудиторий)
CREATE TABLE AUDITORIUM_TYPE
(
    AUDITORIUM_TYPE INT PRIMARY KEY,
    AUDITORIUM_TYPENAME NVARCHAR(30)  -- Используем NVARCHAR вместо NCHAR
);
GO

-- Создание таблицы AUDITORIUM (аудитории)
CREATE TABLE AUDITORIUM
(
    AUDITORIUM INT PRIMARY KEY,
    AUDITORIUM_NAME NVARCHAR(30),  -- Используем NVARCHAR вместо NCHAR
    AUDITORIUM_CAPACITY INT,
    AUDITORIUM_TYPE INT,
    CONSTRAINT FK_Auditoriums_AuditoriumsTypes FOREIGN KEY (AUDITORIUM_TYPE) REFERENCES AUDITORIUM_TYPE(AUDITORIUM_TYPE)
);
GO

-- Вставка данных в таблицу FACULTY
INSERT INTO FACULTY (FACULTY, FACULTY_NAME) VALUES
(1, N'ФИТ'),
(2, N'ХТиТ'),
(3, N'ТОВ'),
(4, N'ИЭФ');
GO

-- Вставка данных в таблицу PULPIT
INSERT INTO PULPIT (PULPIT, PULPIT_NAME, FACULTY) VALUES
(1, N'ИСиТ', 1),
(2, N'ПИ', 1),
(3, N'Дизайн', 1);
GO

-- Вставка данных в таблицу TEACHER
INSERT INTO TEACHER (TEACHER, TEACHER_NAME, PULPIT) VALUES
(1, N'Иванов И.И.', 1),
(2, N'Петров П.П.', 2),
(3, N'Сидоров С.С.', 3);
GO

-- Вставка данных в таблицу SUBJECT
INSERT INTO SUBJECT (SUBJECT, SUBJECT_NAME, PULPIT) VALUES
(1, N'БД', 1),
(2, N'ПСКП', 2),
(3, N'СП', 2),
(4, N'ОС', 1);
GO

-- Вставка данных в таблицу AUDITORIUM_TYPE
INSERT INTO AUDITORIUM_TYPE (AUDITORIUM_TYPE, AUDITORIUM_TYPENAME) VALUES
(1, N'Лекционная'),
(2, N'Лабораторная'),
(3, N'Компьютерная');
GO

-- Вставка данных в таблицу AUDITORIUM
INSERT INTO AUDITORIUM (AUDITORIUM, AUDITORIUM_NAME, AUDITORIUM_CAPACITY, AUDITORIUM_TYPE) VALUES
(1, N'100-3', 120, 1),
(2, N'205-4', 30, 2),
(3, N'310-1', 25, 3);
GO

-- Добавление каскадного удаления и обновления для внешних ключей

-- Пересоздание внешнего ключа для PULPIT с CASCADE
ALTER TABLE PULPIT DROP CONSTRAINT IF EXISTS FK_Pulpits_Facultys;
ALTER TABLE PULPIT ADD CONSTRAINT FK_Pulpits_Facultys 
    FOREIGN KEY (FACULTY) REFERENCES FACULTY(FACULTY) 
    ON DELETE CASCADE ON UPDATE CASCADE;
GO

-- Пересоздание внешнего ключа для TEACHER с CASCADE
ALTER TABLE TEACHER DROP CONSTRAINT IF EXISTS FK_Teachers_Pulpits;
ALTER TABLE TEACHER ADD CONSTRAINT FK_Teachers_Pulpits 
    FOREIGN KEY (PULPIT) REFERENCES PULPIT(PULPIT) 
    ON DELETE CASCADE ON UPDATE CASCADE;
GO

-- Пересоздание внешнего ключа для SUBJECT с CASCADE
ALTER TABLE SUBJECT DROP CONSTRAINT IF EXISTS FK_Subjects_Pulpits;
ALTER TABLE SUBJECT ADD CONSTRAINT FK_Subjects_Pulpits 
    FOREIGN KEY (PULPIT) REFERENCES PULPIT(PULPIT) 
    ON DELETE CASCADE ON UPDATE CASCADE;
GO

-- Пересоздание внешнего ключа для AUDITORIUM с CASCADE
ALTER TABLE AUDITORIUM DROP CONSTRAINT IF EXISTS FK_Auditoriums_AuditoriumsTypes;
ALTER TABLE AUDITORIUM ADD CONSTRAINT FK_Auditoriums_AuditoriumsTypes 
    FOREIGN KEY (AUDITORIUM_TYPE) REFERENCES AUDITORIUM_TYPE(AUDITORIUM_TYPE) 
    ON DELETE CASCADE ON UPDATE CASCADE;
GO

-- Дополнительно: обрезаем пробелы (на всякий случай, хотя при NVARCHAR их не должно быть)
UPDATE FACULTY SET FACULTY_NAME = RTRIM(FACULTY_NAME);
UPDATE PULPIT SET PULPIT_NAME = RTRIM(PULPIT_NAME);
UPDATE TEACHER SET TEACHER_NAME = RTRIM(TEACHER_NAME);
UPDATE SUBJECT SET SUBJECT_NAME = RTRIM(SUBJECT_NAME);
UPDATE AUDITORIUM_TYPE SET AUDITORIUM_TYPENAME = RTRIM(AUDITORIUM_TYPENAME);
UPDATE AUDITORIUM SET AUDITORIUM_NAME = RTRIM(AUDITORIUM_NAME);
GO

-- ПРОВЕРКА: отображение всех данных без пробелов

PRINT '=== ТАБЛИЦА FACULTY ===';
SELECT FACULTY, '[' + FACULTY_NAME + ']' as FACULTY_NAME_WITH_BRACKETS 
FROM FACULTY;
GO

PRINT '=== ТАБЛИЦА PULPIT ===';
SELECT PULPIT, '[' + PULPIT_NAME + ']' as PULPIT_NAME_WITH_BRACKETS, FACULTY
FROM PULPIT;
GO

PRINT '=== ТАБЛИЦА TEACHER ===';
SELECT TEACHER, '[' + TEACHER_NAME + ']' as TEACHER_NAME_WITH_BRACKETS, PULPIT
FROM TEACHER;
GO

PRINT '=== ТАБЛИЦА SUBJECT ===';
SELECT SUBJECT, '[' + SUBJECT_NAME + ']' as SUBJECT_NAME_WITH_BRACKETS, PULPIT
FROM SUBJECT;
GO

PRINT '=== ТАБЛИЦА AUDITORIUM_TYPE ===';
SELECT AUDITORIUM_TYPE, '[' + AUDITORIUM_TYPENAME + ']' as AUDITORIUM_TYPENAME_WITH_BRACKETS
FROM AUDITORIUM_TYPE;
GO

PRINT '=== ТАБЛИЦА AUDITORIUM ===';
SELECT AUDITORIUM, '[' + AUDITORIUM_NAME + ']' as AUDITORIUM_NAME_WITH_BRACKETS, 
       AUDITORIUM_CAPACITY, AUDITORIUM_TYPE
FROM AUDITORIUM;
GO

-- Общая проверка всех таблиц
PRINT '=== ВСЕ ТАБЛИЦЫ С ОБРЕЗАННЫМИ ПРОБЕЛАМИ ===';
SELECT 'FACULTY' as TABLE_NAME, FACULTY as ID, FACULTY_NAME as NAME, 
       '[' + FACULTY_NAME + ']' as NAME_WITH_BRACKETS 
FROM FACULTY
UNION ALL
SELECT 'PULPIT', PULPIT, PULPIT_NAME, '[' + PULPIT_NAME + ']' 
FROM PULPIT
UNION ALL
SELECT 'TEACHER', TEACHER, TEACHER_NAME, '[' + TEACHER_NAME + ']' 
FROM TEACHER
UNION ALL
SELECT 'SUBJECT', SUBJECT, SUBJECT_NAME, '[' + SUBJECT_NAME + ']' 
FROM SUBJECT
UNION ALL
SELECT 'AUDITORIUM_TYPE', AUDITORIUM_TYPE, AUDITORIUM_TYPENAME, 
       '[' + AUDITORIUM_TYPENAME + ']' 
FROM AUDITORIUM_TYPE
UNION ALL
SELECT 'AUDITORIUM', AUDITORIUM, AUDITORIUM_NAME, 
       '[' + AUDITORIUM_NAME + ']' 
FROM AUDITORIUM
ORDER BY TABLE_NAME, ID;
GO