-- Задание 1
SELECT name, open_mode FROM v$pdbs;

-- Задание 2  
SELECT instance_name, host_name, version, status FROM v$instance;

-- Задание 3
SELECT * FROM product_component_version;


-- Задание 4
ALTER SESSION SET CONTAINER = CDB$ROOT;

SELECT SYS_CONTEXT('USERENV', 'CON_NAME') AS current_container FROM dual;

CREATE PLUGGABLE DATABASE RMV_PDB 
ADMIN USER pdb_admin IDENTIFIED BY 1234
ROLES = (DBA)
FILE_NAME_CONVERT = ('pdbseed', 'RMV_PDB');

ALTER PLUGGABLE DATABASE RMV_PDB OPEN;

-- Задание 5
SELECT name, open_mode FROM v$pdbs;


-- Задание 6
ALTER SESSION SET CONTAINER = RMV_PDB;

SELECT SYS_CONTEXT('USERENV', 'CON_NAME') AS current_container FROM dual;

CREATE TABLESPACE TS_PDB_RMV
  DATAFILE 'TS_PDB_RMV.dbf'
  SIZE 7M
  AUTOEXTEND ON NEXT 5M
  MAXSIZE 20M
  EXTENT MANAGEMENT LOCAL;
  
CREATE TEMPORARY TABLESPACE TS_PDB_RMV_TEMP
  TEMPFILE 'TS_PDB_RMV_TEMP.dbf'
  SIZE 5M
  AUTOEXTEND ON NEXT 3M
  MAXSIZE 30M;
  
CREATE ROLE RL_PDB_RMVCORE;
  
GRANT CONNECT, CREATE SESSION, CREATE ANY TABLE, DROP ANY TABLE, 
CREATE ANY VIEW, DROP ANY VIEW, CREATE ANY PROCEDURE, DROP ANY PROCEDURE 
TO RL_PDB_RMVCORE;
  
CREATE PROFILE PF_PDB_RMVCORE LIMIT
  PASSWORD_LIFE_TIME 365
  SESSIONS_PER_USER 5
  FAILED_LOGIN_ATTEMPTS 5
  PASSWORD_LOCK_TIME 1
  PASSWORD_REUSE_TIME 10
  PASSWORD_GRACE_TIME DEFAULT
  CONNECT_TIME 180
  IDLE_TIME 45;
  
CREATE USER U1_RMV_PDB IDENTIFIED BY 12345
DEFAULT TABLESPACE TS_PDB_RMV 
QUOTA UNLIMITED ON TS_PDB_RMV
TEMPORARY TABLESPACE TS_PDB_RMV_TEMP
PROFILE PF_PDB_RMVCORE
ACCOUNT UNLOCK
--PASSWORD EXPIRE;




 
 -------------- Задание 7
ALTER SESSION SET CONTAINER = RMV_PDB;

--ALTER USER U1_RMV_PDB IDENTIFIED BY simple123 ACCOUNT UNLOCK;

GRANT CREATE SESSION TO U1_RMV_PDB;
GRANT CREATE TABLE TO U1_RMV_PDB;
ALTER USER U1_RMV_PDB QUOTA UNLIMITED ON TS_PDB_RMV;

SELECT username, account_status, lock_date, expiry_date 
FROM dba_users 
WHERE username = 'U1_RMV_PDB';

SELECT grantee, privilege FROM dba_sys_privs WHERE grantee = 'U1_RMV_PDB';
SELECT grantee, granted_role FROM dba_role_privs WHERE grantee = 'U1_RMV_PDB';

 

-- Задание 8
ALTER SESSION SET CONTAINER = RMV_PDB;

SELECT tablespace_name, status, contents FROM dba_tablespaces;

SELECT file_name, tablespace_name, bytes/1024/1024 AS size_mb 
FROM dba_data_files;

SELECT file_name, tablespace_name, bytes/1024/1024 AS size_mb 
FROM dba_temp_files;

SELECT grantee, granted_role FROM dba_role_privs;

SELECT DISTINCT profile FROM dba_profiles;

SELECT username, account_status, created FROM dba_users;


-- Задание 9 

ALTER SESSION SET CONTAINER = CDB$ROOT;

CREATE USER C##RMV IDENTIFIED BY 12345 CONTAINER = ALL;

GRANT CREATE SESSION TO C##RMV CONTAINER = ALL;

GRANT CREATE ANY TABLE, DROP ANY TABLE TO C##RMV CONTAINER = ALL;

ALTER USER C##RMV ACCOUNT UNLOCK;

SELECT username, common, con_id, account_status 
FROM cdb_users 
WHERE username = 'C##RMV';


-- Задание 10

ALTER SESSION SET CONTAINER = CDB$ROOT;

ALTER PLUGGABLE DATABASE RMV_PDB CLOSE IMMEDIATE;

DROP PLUGGABLE DATABASE RMV_PDB INCLUDING DATAFILES;

DROP USER C##RMV CASCADE;

SELECT name, open_mode FROM v$pdbs;








