 ALTER SESSION SET NLS_DATE_FORMAT = 'DD-MM-YYYY';

-- Задание № 1
ALTER TABLE TEACHER
    ADD BIRTHDAY DATE;
ALTER TABLE TEACHER
    ADD SALARY NUMBER;

UPDATE TEACHER
SET BIRTHDAY = '12-02-1959'
WHERE TEACHER = 'СМЛВ';
UPDATE TEACHER
SET BIRTHDAY = '30-01-1987'
WHERE TEACHER = 'АКНВЧ';
UPDATE TEACHER
SET BIRTHDAY = '19-04-1991'
WHERE TEACHER = 'КЛСНВ';
UPDATE TEACHER
SET BIRTHDAY = '16-04-1964'
WHERE TEACHER = 'ГРМН';
UPDATE TEACHER
SET BIRTHDAY = '19-11-1988'
WHERE TEACHER = 'ЛЩНК';
UPDATE TEACHER
SET BIRTHDAY = '05-10-1966'
WHERE TEACHER = 'БРКВЧ';
UPDATE TEACHER
SET BIRTHDAY = '10-08-1976'
WHERE TEACHER = 'ДДК';
UPDATE TEACHER
SET BIRTHDAY = '11-09-1989'
WHERE TEACHER = 'КБЛ';
UPDATE TEACHER
SET BIRTHDAY = '24-12-1983'
WHERE TEACHER = 'УРБ';
UPDATE TEACHER
SET BIRTHDAY = '03-06-1990'
WHERE TEACHER = 'РМНК';
UPDATE TEACHER
SET BIRTHDAY = '10-05-1970'
WHERE TEACHER = 'ПСТВЛВ';
UPDATE TEACHER
SET BIRTHDAY = '26-10-1999'
WHERE TEACHER = '?';
UPDATE TEACHER
SET BIRTHDAY = '30-07-1984'
WHERE TEACHER = 'ГРН';
UPDATE TEACHER
SET BIRTHDAY = '11-03-1975'
WHERE TEACHER = 'ЖЛК';
UPDATE TEACHER
SET BIRTHDAY = '12-07-1969'
WHERE TEACHER = 'БРТШВЧ';
UPDATE TEACHER
SET BIRTHDAY = '26-02-1983'
WHERE TEACHER = 'ЮДНКВ';
UPDATE TEACHER
SET BIRTHDAY = '13-12-1991'
WHERE TEACHER = 'БРНВСК';
UPDATE TEACHER
SET BIRTHDAY = '20-01-1968'
WHERE TEACHER = 'НВРВ';
UPDATE TEACHER
SET BIRTHDAY = '21-12-1969'
WHERE TEACHER = 'РВКЧ';
UPDATE TEACHER
SET BIRTHDAY = '28-01-1975'
WHERE TEACHER = 'ДМДК';
UPDATE TEACHER
SET BIRTHDAY = '10-07-1983'
WHERE TEACHER = 'МШКВСК';
UPDATE TEACHER
SET BIRTHDAY = '08-10-1988'
WHERE TEACHER = 'ЛБХ';
UPDATE TEACHER
SET BIRTHDAY = '30-07-1984'
WHERE TEACHER = 'ЗВГЦВ';
UPDATE TEACHER
SET BIRTHDAY = '16-04-1964'
WHERE TEACHER = 'БЗБРДВ';
UPDATE TEACHER
SET BIRTHDAY = '12-05-1985'
WHERE TEACHER = 'ПРКПЧК';
UPDATE TEACHER
SET BIRTHDAY = '20-10-1980'
WHERE TEACHER = 'НСКВЦ';
UPDATE TEACHER
SET BIRTHDAY = '21-08-1990'
WHERE TEACHER = 'МХВ';
UPDATE TEACHER
SET BIRTHDAY = '13-08-1966'
WHERE TEACHER = 'ЕЩНК';
UPDATE TEACHER
SET BIRTHDAY = '11-11-1978'
WHERE TEACHER = 'ЖРСК';

UPDATE TEACHER
SET SALARY = 1030
WHERE TEACHER = 'СМЛВ';
UPDATE TEACHER
SET SALARY = 1030
WHERE TEACHER = 'АКНВЧ';
UPDATE TEACHER
SET SALARY = 980
WHERE TEACHER = 'КЛСНВ';
UPDATE TEACHER
SET SALARY = 1050
WHERE TEACHER = 'ГРМН';
UPDATE TEACHER
SET SALARY = 590
WHERE TEACHER = 'ЛЩНК';
UPDATE TEACHER
SET SALARY = 870
WHERE TEACHER = 'БРКВЧ';
UPDATE TEACHER
SET SALARY = 815
WHERE TEACHER = 'ДДК';
UPDATE TEACHER
SET SALARY = 995
WHERE TEACHER = 'КБЛ';
UPDATE TEACHER
SET SALARY = 1460
WHERE TEACHER = 'УРБ';
UPDATE TEACHER
SET SALARY = 1120
WHERE TEACHER = 'РМНК';
UPDATE TEACHER
SET SALARY = 1250
WHERE TEACHER = 'ПСТВЛВ';
UPDATE TEACHER
SET SALARY = 333
WHERE TEACHER = '?';
UPDATE TEACHER
SET SALARY = 1520
WHERE TEACHER = 'ГРН';
UPDATE TEACHER
SET SALARY = 1430
WHERE TEACHER = 'ЖЛК';
UPDATE TEACHER
SET SALARY = 900
WHERE TEACHER = 'БРТШВЧ';
UPDATE TEACHER
SET SALARY = 875
WHERE TEACHER = 'ЮДНКВ';
UPDATE TEACHER
SET SALARY = 970
WHERE TEACHER = 'БРНВСК';
UPDATE TEACHER
SET SALARY = 780
WHERE TEACHER = 'НВРВ';
UPDATE TEACHER
SET SALARY = 1150
WHERE TEACHER = 'РВКЧ';
UPDATE TEACHER
SET SALARY = 805
WHERE TEACHER = 'ДМДК';
UPDATE TEACHER
SET SALARY = 905
WHERE TEACHER = 'МШКВСК';
UPDATE TEACHER
SET SALARY = 1200
WHERE TEACHER = 'ЛБХ';
UPDATE TEACHER
SET SALARY = 1500
WHERE TEACHER = 'ЗВГЦВ';
UPDATE TEACHER
SET SALARY = 905
WHERE TEACHER = 'БЗБРДВ';
UPDATE TEACHER
SET SALARY = 715
WHERE TEACHER = 'ПРКПЧК';
UPDATE TEACHER
SET SALARY = 880
WHERE TEACHER = 'НСКВЦ';
UPDATE TEACHER
SET SALARY = 735
WHERE TEACHER = 'МХВ';
UPDATE TEACHER
SET SALARY = 595
WHERE TEACHER = 'ЕЩНК';
UPDATE TEACHER
SET SALARY = 850
WHERE TEACHER = 'ЖРСК';

COMMIT;

SELECT * FROM TEACHER;

-- Задание № 2
SELECT REGEXP_SUBSTR(TEACHER_NAME, '(\S+)', 1, 1) || ' ' ||
       SUBSTR(REGEXP_SUBSTR(TEACHER_NAME, '(\S+)', 1, 2), 1, 1) || '. ' ||
       SUBSTR(REGEXP_SUBSTR(TEACHER_NAME, '(\S+)', 1, 3), 1, 1) || '.' AS ФИО
FROM TEACHER;


-- Задание № 3
SELECT *
FROM TEACHER
WHERE TO_CHAR(BIRTHDAY, 'd') = 2;


-- Задание № 4
DROP VIEW NEXT_MONTH;

CREATE OR REPLACE VIEW NEXT_MONTH AS
SELECT *
FROM TEACHER
WHERE TO_CHAR(BIRTHDAY, 'mm') = TO_CHAR(ADD_MONTHS(SYSDATE, 1), 'mm');

SELECT * FROM NEXT_MONTH;


-- Задание № 5
--DROP VIEW NUMBER_MONTHS;

CREATE OR REPLACE VIEW NUMBER_MONTHS AS
SELECT TO_CHAR(BIRTHDAY, 'Month') AS МЕСЯЦ,
       COUNT(*) AS КОЛИЧЕСТВО
FROM TEACHER
GROUP BY TO_CHAR(BIRTHDAY, 'Month')
ORDER BY КОЛИЧЕСТВО DESC;

SELECT * FROM NUMBER_MONTHS;


-- Задание № 6
DECLARE
    CURSOR TEACHER_BIRTHDAY IS
        SELECT TEACHER, TEACHER_NAME, PULPIT, BIRTHDAY, SALARY
        FROM TEACHER
        WHERE MOD((EXTRACT(YEAR FROM SYSDATE) - EXTRACT(YEAR FROM BIRTHDAY) + 1), 10) = 0;
    V_TEACHER  TEACHER%ROWTYPE;
BEGIN
    OPEN TEACHER_BIRTHDAY;
    LOOP
        FETCH TEACHER_BIRTHDAY INTO V_TEACHER;
        EXIT WHEN TEACHER_BIRTHDAY%NOTFOUND;
        DBMS_OUTPUT.PUT_LINE(V_TEACHER.TEACHER || ' ' || V_TEACHER.TEACHER_NAME || ' ' || 
                           V_TEACHER.PULPIT || ' ' || V_TEACHER.BIRTHDAY || ' ' || V_TEACHER.SALARY);
    END LOOP;
    CLOSE TEACHER_BIRTHDAY;
END;
/


-- Задание № 7
DECLARE
    CURSOR TEACHERS_AVG_SALARY IS
        SELECT PULPIT, FLOOR(AVG(SALARY)) AS AVG_SALARY
        FROM TEACHER
        GROUP BY PULPIT;
    
    CURSOR FACULTY_AVG_SALARY IS
        SELECT F.FACULTY, FLOOR(AVG(T.SALARY)) AS AVG_SALARY
        FROM TEACHER T
        JOIN PULPIT P ON T.PULPIT = P.PULPIT
        JOIN FACULTY F ON P.FACULTY = F.FACULTY
        GROUP BY F.FACULTY;
    
    V_PULPIT  TEACHER.PULPIT%TYPE;
    V_SALARY  NUMBER;
    V_FACULTY FACULTY.FACULTY%TYPE;
    V_OVERALL_AVG NUMBER;
BEGIN
    DBMS_OUTPUT.PUT_LINE('--------------- ПО КАФЕДРАМ -----------------');
    OPEN TEACHERS_AVG_SALARY;
    LOOP
        FETCH TEACHERS_AVG_SALARY INTO V_PULPIT, V_SALARY;
        EXIT WHEN TEACHERS_AVG_SALARY%NOTFOUND;
        DBMS_OUTPUT.PUT_LINE(V_PULPIT || ' ' || V_SALARY);
    END LOOP;
    CLOSE TEACHERS_AVG_SALARY;

    DBMS_OUTPUT.PUT_LINE('--------------- ПО ФАКУЛЬТЕТАМ -----------------');
    OPEN FACULTY_AVG_SALARY;
    LOOP
        FETCH FACULTY_AVG_SALARY INTO V_FACULTY, V_SALARY;
        EXIT WHEN FACULTY_AVG_SALARY%NOTFOUND;
        DBMS_OUTPUT.PUT_LINE(V_FACULTY || ' ' || V_SALARY);
    END LOOP;
    CLOSE FACULTY_AVG_SALARY;

    DBMS_OUTPUT.PUT_LINE('--------------- ПО ВСЕМ ФАКУЛЬТЕТАМ -----------------');
    SELECT FLOOR(AVG(SALARY)) INTO V_OVERALL_AVG FROM TEACHER;
    DBMS_OUTPUT.PUT_LINE('Средняя зарплата: ' || V_OVERALL_AVG);
END;
/


-- Задание № 8
DECLARE
    TYPE SUPPLIERTYPE IS RECORD (
        SUPPLIERNAME VARCHAR2(100),
        SUPPLIERLOCATION VARCHAR2(50)
    );
    
    TYPE PRODUCTTYPE IS RECORD (
        PRODUCTNAME VARCHAR2(100),
        PRICE NUMBER,
        QUANTITY NUMBER,
        SUPPLIERINFO SUPPLIERTYPE
    );
    
    PRODUCT_INFO  PRODUCTTYPE;
    SUPPLIER_INFO SUPPLIERTYPE;
    PRODUCT_INFO_2 PRODUCTTYPE;
BEGIN
    SUPPLIER_INFO.SUPPLIERNAME := 'Поставщик 1';
    SUPPLIER_INFO.SUPPLIERLOCATION := 'Минск';
    
    PRODUCT_INFO.PRODUCTNAME := 'Телевизор';
    PRODUCT_INFO.PRICE := 999.99;
    PRODUCT_INFO.QUANTITY := 100;
    PRODUCT_INFO.SUPPLIERINFO := SUPPLIER_INFO;

    DBMS_OUTPUT.PUT_LINE('ТОВАР: ' || PRODUCT_INFO.PRODUCTNAME);
    DBMS_OUTPUT.PUT_LINE('ЦЕНА: $' || PRODUCT_INFO.PRICE);
    DBMS_OUTPUT.PUT_LINE('КОЛИЧЕСТВО: ' || PRODUCT_INFO.QUANTITY);
    DBMS_OUTPUT.PUT_LINE('ПОСТАВЩИК: ' || PRODUCT_INFO.SUPPLIERINFO.SUPPLIERNAME);
    DBMS_OUTPUT.PUT_LINE('ГОРОД: ' || PRODUCT_INFO.SUPPLIERINFO.SUPPLIERLOCATION);

    DBMS_OUTPUT.PUT_LINE('--- ДЕМОНСТРАЦИЯ ПРИСВОЕНИЯ ---');
    PRODUCT_INFO_2 := PRODUCT_INFO;
    PRODUCT_INFO_2.PRICE := 899.99;
    
    DBMS_OUTPUT.PUT_LINE('ТОВАР 2: ' || PRODUCT_INFO_2.PRODUCTNAME);
    DBMS_OUTPUT.PUT_LINE('НОВАЯ ЦЕНА: $' || PRODUCT_INFO_2.PRICE);
END;
/
