error_log D:/Univer/3_kurs/6sem/TRwP/Lab_02/nginx_error.log debug;
access_log D:/Univer/3_kurs/6sem/TRwP/Lab_02/nginx_access.log;

server {
    listen 20000;
    server_name localhost;
    charset utf-8;

    # Задание 1: TDWA02-01
    location / {
        root D:/Univer/3_kurs/6sem/TRwP/Lab_02/tdwa02-01;
        index TDWA02-01.html;
    }

    # Задание 2: TDWA02-02
    location /TDWA02-02/ {
        root D:/Univer/3_kurs/6sem/TRwP/Lab_02/tdwa02-02/build/;
        index TDWA02-01.html;
    }

    # API
    location /api/Save-JSON {
        proxy_pass http://localhost:40000/NGINX-test;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_buffering off;
    }
}