-- ОЧИСТКА СОЗДАННЫХ ТАБЛИЦ
DROP TABLE KEEP_POOL_TABLE;
DROP TABLE DEFAULT_CACHE_TABLE;

-- ПРОВЕРКА, ЧТО ТАБЛИЦЫ УДАЛЕНЫ
SELECT SEGMENT_NAME, SEGMENT_TYPE, TABLESPACE_NAME, BUFFER_POOL
FROM USER_SEGMENTS 
WHERE SEGMENT_NAME IN ('KEEP_POOL_TABLE', 'DEFAULT_CACHE_TABLE');

-- ОЧИСТКА КЭША (ОПЦИОНАЛЬНО)
ALTER SYSTEM FLUSH BUFFER_CACHE;