---- ЗАДАНИЕ 1
SELECT SUM(VALUE) TOTAL_SGA_IN_BYTES FROM V$SGA;

---- ЗАДАНИЕ 2
SELECT NAME POOL_NAME, VALUE SIZE_IN_BYTES FROM V$SGA;

---- ЗАДАНИЕ 3 
SELECT COMPONENT, GRANULE_SIZE FROM V$SGA_DYNAMIC_COMPONENTS;

---- ЗАДАНИЕ 4
SELECT CURRENT_SIZE FROM V$SGA_DYNAMIC_FREE_MEMORY;

---- ЗАДАНИЕ 5
SELECT NAME, VALUE FROM V$PARAMETER 
WHERE NAME IN ('SGA_TARGET', 'SGA_MAX_SIZE');

---- ЗАДАНИЕ 6
SELECT COMPONENT, MIN_SIZE, MAX_SIZE, CURRENT_SIZE FROM V$SGA_DYNAMIC_COMPONENTS
WHERE COMPONENT IN ('KEEP BUFFER CACHE', 'RECYCLE BUFFER CACHE', 'DEFAULT BUFFER CACHE');

---- ЗАДАНИЕ 7
CREATE TABLE KEEP_POOL_TABLE (NUM NUMBER) STORAGE (BUFFER_POOL KEEP);
INSERT INTO KEEP_POOL_TABLE VALUES (1);
INSERT INTO KEEP_POOL_TABLE VALUES (2);
INSERT INTO KEEP_POOL_TABLE VALUES (3);
COMMIT;

SELECT SEGMENT_NAME, SEGMENT_TYPE, TABLESPACE_NAME, BUFFER_POOL
FROM USER_SEGMENTS WHERE SEGMENT_NAME LIKE 'KEEP%';

---- ЗАДАНИЕ 8
CREATE TABLE DEFAULT_CACHE_TABLE (NUM NUMBER) STORAGE (BUFFER_POOL DEFAULT);
INSERT INTO DEFAULT_CACHE_TABLE VALUES (4);
INSERT INTO DEFAULT_CACHE_TABLE VALUES (5);
COMMIT;

SELECT SEGMENT_NAME, SEGMENT_TYPE, TABLESPACE_NAME, BUFFER_POOL
FROM USER_SEGMENTS WHERE SEGMENT_NAME LIKE 'DEFAULT_CACHE%';

---- ЗАДАНИЕ 9
SHOW PARAMETER LOG_BUFFER;

---- ЗАДАНИЕ 10
SELECT POOL, NAME, BYTES FROM V$SGASTAT WHERE POOL = '%LARGE%';

---- ЗАДАНИЕ 11
SELECT SID, STATUS, SERVER, LOGON_TIME, PROGRAM, OSUSER, MACHINE, USERNAME, STATE
FROM V$SESSION
WHERE STATUS = 'ACTIVE';

---- ЗАДАНИЕ 12
SELECT SID, PROCESS, NAME, DESCRIPTION, PROGRAM
FROM V$SESSION S JOIN V$BGPROCESS USING (PADDR)
WHERE S.STATUS = 'ACTIVE';

---- ЗАДАНИЕ 13
SELECT * FROM V$PROCESS;

---- ЗАДАНИЕ 14
SELECT COUNT(*) FROM V$PROCESS WHERE PNAME LIKE 'DBW%';

---- ЗАДАНИЕ 15
SELECT NAME, NETWORK_NAME, PDB FROM V$SERVICES;

---- ЗАДАНИЕ 16
SHOW PARAMETER DISPATCHERS;