-- =====================================================
-- 1. СОЗДАНИЕ ТАБЛИЦ
-- =====================================================
-- Таблица 1: User (Пользователи)
CREATE TABLE "User" (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email VARCHAR2(255) NOT NULL UNIQUE,
    password_hash VARCHAR2(255) NOT NULL,
    first_name VARCHAR2(100) NOT NULL,
    last_name VARCHAR2(100) NOT NULL,
    phone VARCHAR2(20),
    registration_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    last_login TIMESTAMP,
    role VARCHAR2(20) NOT NULL CHECK (role IN ('client', 'manager'))
);

-- Таблица 2: Client (Клиенты)
CREATE TABLE Client (
    user_id NUMBER PRIMARY KEY,
    passport_number VARCHAR2(50) NOT NULL,
    passport_issue_date DATE NOT NULL,
    passport_expiry_date DATE NOT NULL,
    date_of_birth DATE NOT NULL,
    loyalty_points NUMBER DEFAULT 0,
    client_since DATE,
    CONSTRAINT fk_client_user FOREIGN KEY (user_id) REFERENCES "User"(id) ON DELETE CASCADE
);

-- Таблица 3: Manager (Менеджеры)
CREATE TABLE Manager (
    user_id NUMBER PRIMARY KEY,
    employee_id VARCHAR2(20) NOT NULL UNIQUE,
    hire_date DATE NOT NULL,
    department VARCHAR2(100),
    commission_rate NUMBER(5,2) DEFAULT 0.0,
    CONSTRAINT fk_manager_user FOREIGN KEY (user_id) REFERENCES "User"(id) ON DELETE CASCADE
);

-- Таблица 4: Country (Страны)
CREATE TABLE Country (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR2(100) NOT NULL UNIQUE,
    code CHAR(2) UNIQUE,
    visa_required NUMBER(1) DEFAULT 0 CHECK (visa_required IN (0,1)),
    description CLOB,
    is_popular NUMBER(1) DEFAULT 0 CHECK (is_popular IN (0,1))
);

-- Таблица 5: Hotel (Отели)
CREATE TABLE Hotel (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR2(200) NOT NULL,
    country_id NUMBER NOT NULL,
    city VARCHAR2(100) NOT NULL,
    stars NUMBER(1) CHECK (stars BETWEEN 1 AND 5),
    food_type VARCHAR2(50) CHECK (food_type IN ('RO', 'BB', 'HB', 'FB', 'AI')),
    rating NUMBER(3,1) CHECK (rating BETWEEN 0 AND 5),
    address CLOB,
    contact_phone VARCHAR2(20),
    CONSTRAINT fk_hotel_country FOREIGN KEY (country_id) REFERENCES Country(id)
);

-- Таблица 6: TourType (Типы туров)
CREATE TABLE TourType (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR2(100) NOT NULL UNIQUE,
    description CLOB,
    seasonality VARCHAR2(20) CHECK (seasonality IN ('summer', 'winter', 'all')),
    activity_level VARCHAR2(20) CHECK (activity_level IN ('low', 'medium', 'high'))
);

-- Таблица 7: Flight (Рейсы)
CREATE TABLE Flight (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    airline VARCHAR2(150) NOT NULL,
    flight_number VARCHAR2(10) NOT NULL,
    departure_airport VARCHAR2(100) NOT NULL,
    arrival_airport VARCHAR2(100) NOT NULL,
    departure_datetime TIMESTAMP NOT NULL,
    arrival_datetime TIMESTAMP NOT NULL,
    flight_class VARCHAR2(50) CHECK (flight_class IN ('economy', 'business', 'first')),
    is_included NUMBER(1) DEFAULT 1 CHECK (is_included IN (0,1))
);

-- Таблица 8: Tour (Туры)
CREATE TABLE Tour (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR2(255) NOT NULL,
    description CLOB,
    tour_type_id NUMBER,
    country_id NUMBER NOT NULL,
    hotel_id NUMBER NOT NULL,
    flight_id NUMBER,
    duration_days NUMBER NOT NULL,
    departure_date DATE NOT NULL,
    base_price NUMBER(10,2) NOT NULL,
    available_seats NUMBER NOT NULL,
    is_active NUMBER(1) DEFAULT 1 CHECK (is_active IN (0,1)),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_tour_type FOREIGN KEY (tour_type_id) REFERENCES TourType(id),
    CONSTRAINT fk_tour_country FOREIGN KEY (country_id) REFERENCES Country(id),
    CONSTRAINT fk_tour_hotel FOREIGN KEY (hotel_id) REFERENCES Hotel(id),
    CONSTRAINT fk_tour_flight FOREIGN KEY (flight_id) REFERENCES Flight(id)
);

-- Таблица 9: OrderStatus (Статусы заказов)
CREATE TABLE OrderStatus (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR2(50) NOT NULL UNIQUE,
    description CLOB,
    is_final NUMBER(1) DEFAULT 0 CHECK (is_final IN (0,1))
);

-- Таблица 10: Booking (Заказы/Бронирования)
CREATE TABLE Booking (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    booking_number VARCHAR2(50) NOT NULL UNIQUE,
    client_id NUMBER NOT NULL,
    tour_id NUMBER NOT NULL,
    manager_id NUMBER,
    booking_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    status_id NUMBER NOT NULL,
    persons_count NUMBER DEFAULT 1,
    total_price NUMBER(10,2) NOT NULL,
    CONSTRAINT fk_booking_client FOREIGN KEY (client_id) REFERENCES Client(user_id),
    CONSTRAINT fk_booking_tour FOREIGN KEY (tour_id) REFERENCES Tour(id),
    CONSTRAINT fk_booking_manager FOREIGN KEY (manager_id) REFERENCES Manager(user_id),
    CONSTRAINT fk_booking_status FOREIGN KEY (status_id) REFERENCES OrderStatus(id)
);

-- Таблица 11: Payment (Платежи)
CREATE TABLE Payment (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    booking_id NUMBER NOT NULL,
    amount NUMBER(10,2) NOT NULL,
    payment_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    payment_method VARCHAR2(50) NOT NULL CHECK (payment_method IN ('card', 'transfer', 'cash')),
    status VARCHAR2(50) NOT NULL CHECK (status IN ('pending', 'completed', 'failed', 'refunded')),
    transaction_id VARCHAR2(255),
    CONSTRAINT fk_payment_booking FOREIGN KEY (booking_id) REFERENCES Booking(id)
);

-- Таблица 12: Review (Отзывы)
CREATE TABLE Review (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    booking_id NUMBER NOT NULL UNIQUE,
    client_id NUMBER NOT NULL,
    tour_id NUMBER NOT NULL,
    rating NUMBER(1) NOT NULL CHECK (rating BETWEEN 1 AND 5),
    review_comment CLOB,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    is_approved NUMBER(1) DEFAULT 0 CHECK (is_approved IN (0,1)),
    CONSTRAINT fk_review_booking FOREIGN KEY (booking_id) REFERENCES Booking(id),
    CONSTRAINT fk_review_client FOREIGN KEY (client_id) REFERENCES Client(user_id),
    CONSTRAINT fk_review_tour FOREIGN KEY (tour_id) REFERENCES Tour(id)
);
/

-- =====================================================
-- 2. ИНДЕКСЫ
-- =====================================================
CREATE INDEX IX_TOUR_COUNTRY ON Tour(country_id);
CREATE INDEX IX_TOUR_DEPARTURE ON Tour(departure_date);
CREATE INDEX IX_BOOKING_CLIENT ON Booking(client_id);
CREATE INDEX IX_BOOKING_STATUS ON Booking(status_id);
CREATE INDEX IX_PAYMENT_BOOKING ON Payment(booking_id);
/

-- =====================================================
-- 3. ПРЕДСТАВЛЕНИЯ
-- =====================================================
CREATE OR REPLACE VIEW V_ACTIVE_TOURS AS
SELECT
    t.id AS TourId,
    t.title,
    t.base_price,
    t.duration_days,
    t.departure_date,
    t.available_seats,
    c.name AS Country,
    h.name AS Hotel,
    h.stars,
    tt.name AS TourType
FROM Tour t
INNER JOIN Country c ON t.country_id = c.id
INNER JOIN Hotel h ON t.hotel_id = h.id
LEFT JOIN TourType tt ON t.tour_type_id = tt.id
WHERE t.is_active = 1;
/

CREATE OR REPLACE VIEW V_BOOKING_REPORT AS
SELECT
    b.booking_number,
    u.first_name || ' ' || u.last_name AS ClientName,
    t.title AS TourTitle,
    b.booking_date,
    os.name AS Status,
    b.persons_count,
    b.total_price,
    p.amount AS PaidAmount,
    p.status AS PaymentStatus
FROM Booking b
INNER JOIN Client c ON b.client_id = c.user_id
INNER JOIN "User" u ON c.user_id = u.id
INNER JOIN Tour t ON b.tour_id = t.id
INNER JOIN OrderStatus os ON b.status_id = os.id
LEFT JOIN Payment p ON b.id = p.booking_id;
/

-- =====================================================
-- 4. ТРИГГЕРЫ
-- =====================================================
CREATE OR REPLACE TRIGGER TRG_UPDATE_HOTEL_RATING
    FOR INSERT OR UPDATE ON Review
    COMPOUND TRIGGER

    TYPE hotel_ids_t IS TABLE OF Hotel.id%TYPE INDEX BY PLS_INTEGER;
    hotel_ids  hotel_ids_t;
    v_idx      PLS_INTEGER := 0;

    BEFORE STATEMENT IS
    BEGIN
        hotel_ids.DELETE;
        v_idx := 0;
    END BEFORE STATEMENT;

    AFTER EACH ROW IS
        v_hotel_id Hotel.id%TYPE;
    BEGIN
        BEGIN
            SELECT t.hotel_id INTO v_hotel_id
            FROM Tour t
            INNER JOIN Booking b ON t.id = b.tour_id
            WHERE b.id = :NEW.booking_id;

            IF v_hotel_id IS NOT NULL THEN
                hotel_ids(v_idx) := v_hotel_id;
                v_idx := v_idx + 1;
            END IF;
        EXCEPTION
            WHEN NO_DATA_FOUND THEN
                NULL;
        END;
    END AFTER EACH ROW;

    AFTER STATEMENT IS
    BEGIN
        IF hotel_ids.COUNT > 0 THEN
            FORALL i IN hotel_ids.FIRST..hotel_ids.LAST
                UPDATE Hotel h
                SET rating = (
                    SELECT AVG(r.rating)
                    FROM Review r
                    JOIN Booking b ON r.booking_id = b.id
                    JOIN Tour t ON b.tour_id = t.id
                    WHERE t.hotel_id = hotel_ids(i)
                      AND r.is_approved = 1
                )
                WHERE h.id = hotel_ids(i);
        END IF;
    END AFTER STATEMENT;

END TRG_UPDATE_HOTEL_RATING;
/

SET SERVEROUTPUT ON;
/

-- =====================================================
-- 5. ХРАНИМЫЕ ПРОЦЕДУРЫ
-- =====================================================

-- Процедура 1: Статистика клиента
CREATE OR REPLACE PROCEDURE SP_GET_CLIENT_STATISTICS (
    p_client_id IN Client.user_id%TYPE,
    p_total_spent OUT NUMBER,
    p_total_bookings OUT NUMBER,
    p_avg_check OUT NUMBER
) IS
BEGIN
    SELECT NVL(SUM(b.total_price), 0),
           COUNT(DISTINCT b.id),
           NVL(AVG(b.total_price), 0)
    INTO p_total_spent, p_total_bookings, p_avg_check
    FROM Booking b
    INNER JOIN OrderStatus os ON b.status_id = os.id
    WHERE b.client_id = p_client_id AND os.name = 'completed';
END SP_GET_CLIENT_STATISTICS;
/

-- Процедура 2: Изменение статуса бронирования
CREATE OR REPLACE PROCEDURE SP_CHANGE_BOOKING_STATUS (
    p_booking_number IN Booking.booking_number%TYPE,
    p_new_status_name IN OrderStatus.name%TYPE
) IS
    v_current_status_id OrderStatus.id%TYPE;
    v_is_final OrderStatus.is_final%TYPE;
    v_new_status_id OrderStatus.id%TYPE;
    v_booking_id Booking.id%TYPE;
BEGIN
    SELECT b.status_id, os.is_final, b.id
    INTO v_current_status_id, v_is_final, v_booking_id
    FROM Booking b
    INNER JOIN OrderStatus os ON b.status_id = os.id
    WHERE b.booking_number = p_booking_number
    FOR UPDATE;

    IF v_is_final = 1 THEN
        RAISE_APPLICATION_ERROR(-20001, 'Cannot change status of a booking that is in a final state.');
    END IF;

    SELECT id INTO v_new_status_id FROM OrderStatus WHERE name = p_new_status_name;

    UPDATE Booking SET status_id = v_new_status_id WHERE booking_number = p_booking_number;
    COMMIT;
EXCEPTION
    WHEN NO_DATA_FOUND THEN
        ROLLBACK;
        RAISE_APPLICATION_ERROR(-20002, 'Booking number or new status name not found.');
    WHEN OTHERS THEN
        ROLLBACK;
        RAISE;
END SP_CHANGE_BOOKING_STATUS;
/

-- Процедура 3: Поиск туров
CREATE OR REPLACE PROCEDURE SP_SEARCH_TOURS (
    p_country_name IN Country.name%TYPE DEFAULT NULL,
    p_min_price IN Tour.base_price%TYPE DEFAULT NULL,
    p_max_price IN Tour.base_price%TYPE DEFAULT NULL,
    p_start_date IN Tour.departure_date%TYPE DEFAULT NULL,
    p_duration IN Tour.duration_days%TYPE DEFAULT NULL,
    p_results OUT SYS_REFCURSOR
) IS
BEGIN
    OPEN p_results FOR
        SELECT
            t.id, t.title, t.base_price, t.duration_days, t.departure_date,
            c.name AS Country, h.name AS Hotel
        FROM Tour t
        INNER JOIN Country c ON t.country_id = c.id
        INNER JOIN Hotel h ON t.hotel_id = h.id
        WHERE t.is_active = 1
          AND (p_country_name IS NULL OR c.name LIKE '%' || p_country_name || '%')
          AND (p_min_price IS NULL OR t.base_price >= p_min_price)
          AND (p_max_price IS NULL OR t.base_price <= p_max_price)
          AND (p_start_date IS NULL OR t.departure_date >= p_start_date)
          AND (p_duration IS NULL OR t.duration_days = p_duration);
END SP_SEARCH_TOURS;
/

-- Процедура 4: Отмена бронирования
CREATE OR REPLACE PROCEDURE SP_CANCEL_BOOKING (
    p_booking_number IN Booking.booking_number%TYPE
) IS
    v_cancelled_status_id OrderStatus.id%TYPE;
    v_booking_id Booking.id%TYPE;
BEGIN
    SELECT id INTO v_cancelled_status_id FROM OrderStatus WHERE name = 'cancelled';
    SELECT id INTO v_booking_id FROM Booking WHERE booking_number = p_booking_number;

    UPDATE Booking SET status_id = v_cancelled_status_id WHERE booking_number = p_booking_number;

    UPDATE Payment
    SET status = 'refunded'
    WHERE booking_id = v_booking_id AND status = 'completed';
    COMMIT;
EXCEPTION
    WHEN NO_DATA_FOUND THEN
        ROLLBACK;
        RAISE_APPLICATION_ERROR(-20003, 'Booking number or cancelled status not found.');
    WHEN OTHERS THEN
        ROLLBACK;
        RAISE;
END SP_CANCEL_BOOKING;
/

-- Процедура 5: Расчет комиссии менеджера
CREATE OR REPLACE PROCEDURE SP_GET_MANAGER_COMMISSION (
    p_manager_id IN Manager.user_id%TYPE,
    p_start_date IN DATE,
    p_end_date IN DATE,
    p_total_commission OUT NUMBER
) IS
BEGIN
    SELECT NVL(SUM(b.total_price * m.commission_rate / 100), 0)
    INTO p_total_commission
    FROM Booking b
    INNER JOIN Manager m ON b.manager_id = m.user_id
    INNER JOIN OrderStatus os ON b.status_id = os.id
    WHERE b.manager_id = p_manager_id
      AND os.name = 'completed'
      AND b.booking_date BETWEEN p_start_date AND p_end_date;
END SP_GET_MANAGER_COMMISSION;
/

-- =====================================================
-- 6. ФУНКЦИИ (Functions)
-- =====================================================

-- Функция 1: Возраст клиента
CREATE OR REPLACE FUNCTION FN_GET_CLIENT_AGE (
    p_client_id IN Client.user_id%TYPE
) RETURN NUMBER IS
    v_age NUMBER;
BEGIN
    SELECT FLOOR(MONTHS_BETWEEN(SYSDATE, date_of_birth) / 12)
    INTO v_age
    FROM Client
    WHERE user_id = p_client_id;
    RETURN v_age;
END FN_GET_CLIENT_AGE;
/

-- Функция 2: Проверка доступности мест
CREATE OR REPLACE FUNCTION FN_CHECK_SEAT_AVAILABILITY (
    p_tour_id IN Tour.id%TYPE,
    p_requested_seats IN Tour.available_seats%TYPE
) RETURN NUMBER IS
    v_available_seats Tour.available_seats%TYPE;
BEGIN
    SELECT available_seats INTO v_available_seats
    FROM Tour
    WHERE id = p_tour_id;

    IF v_available_seats >= p_requested_seats THEN
        RETURN 1;
    ELSE
        RETURN 0;
    END IF;
EXCEPTION
    WHEN NO_DATA_FOUND THEN
        RETURN 0;
END FN_CHECK_SEAT_AVAILABILITY;
/

-- Функция 3: Прибыльность тура
CREATE OR REPLACE FUNCTION FN_GET_TOUR_PROFITABILITY (
    p_tour_id IN Tour.id%TYPE
) RETURN NUMBER IS
    v_profit NUMBER := 0;
BEGIN
    SELECT NVL(SUM(p.amount), 0) - (t.base_price * COUNT(DISTINCT b.id))
    INTO v_profit
    FROM Tour t
    LEFT JOIN Booking b ON t.id = b.tour_id
    LEFT JOIN Payment p ON b.id = p.booking_id AND p.status = 'completed'
    WHERE t.id = p_tour_id
    GROUP BY t.base_price;

    RETURN NVL(v_profit, 0);
EXCEPTION
    WHEN NO_DATA_FOUND THEN
        RETURN 0;
END FN_GET_TOUR_PROFITABILITY;
/

-- Функция 4: Рейтинг отелей
CREATE OR REPLACE TYPE hotel_rating_row AS OBJECT (
    id NUMBER,
    HotelName VARCHAR2(200),
    AvgRating NUMBER,
    ReviewCount NUMBER
);
/

CREATE OR REPLACE TYPE hotel_rating_table AS TABLE OF hotel_rating_row;
/

CREATE OR REPLACE FUNCTION FN_GET_HOTEL_RATING_TABLE
RETURN hotel_rating_table PIPELINED IS
    v_rec hotel_rating_row;
BEGIN
    FOR rec IN (
        SELECT
            h.id,
            h.name AS HotelName,
            AVG(r.rating) AS AvgRating,
            COUNT(r.id) AS ReviewCount
        FROM Hotel h
        LEFT JOIN Tour t ON h.id = t.hotel_id
        LEFT JOIN Booking b ON t.id = b.tour_id
        LEFT JOIN Review r ON b.id = r.booking_id AND r.is_approved = 1
        GROUP BY h.id, h.name
        ORDER BY h.id
    ) LOOP
        v_rec := hotel_rating_row(rec.id, rec.HotelName, rec.AvgRating, rec.ReviewCount);
        PIPE ROW (v_rec);
    END LOOP;
    RETURN;
END FN_GET_HOTEL_RATING_TABLE;
/



-- Функция 5: Форматирование имени клиента
CREATE OR REPLACE FUNCTION FN_FORMAT_CLIENT_NAME (
    p_client_id IN Client.user_id%TYPE
) RETURN VARCHAR2 IS
    v_formatted_name VARCHAR2(255);
BEGIN
    SELECT last_name || ' ' || SUBSTR(first_name, 1, 1) || '.'
    INTO v_formatted_name
    FROM "User" u
    INNER JOIN Client c ON u.id = c.user_id
    WHERE c.user_id = p_client_id;
    RETURN v_formatted_name;
END FN_FORMAT_CLIENT_NAME;
/



-- Функция 1: Количество завершенных бронирований клиента
CREATE OR REPLACE FUNCTION FN_GET_CLIENT_COMPLETED_BOOKINGS (
    p_client_id IN Client.user_id%TYPE
) RETURN NUMBER IS
    v_bookings_count NUMBER;
BEGIN
    SELECT COUNT(b.id)
    INTO v_bookings_count
    FROM Booking b
    INNER JOIN OrderStatus os ON b.status_id = os.id
    WHERE b.client_id = p_client_id AND os.name = 'completed';
    
    RETURN NVL(v_bookings_count, 0);
END FN_GET_CLIENT_COMPLETED_BOOKINGS;
/



-- Функция 5: Средняя стоимость туров по стране
CREATE OR REPLACE FUNCTION FN_GET_AVG_TOUR_PRICE_BY_COUNTRY (
    p_country_id IN Country.id%TYPE
) RETURN NUMBER IS
    v_avg_price NUMBER;
BEGIN
    SELECT AVG(base_price)
    INTO v_avg_price
    FROM Tour
    WHERE country_id = p_country_id AND is_active = 1;
    
    RETURN NVL(v_avg_price, 0);
END FN_GET_AVG_TOUR_PRICE_BY_COUNTRY;
/